/* Generated by tools/gen_battle_data.py. Do not edit. */

#include "global.h"
#include "battle.h"
#include "battle_anim.h"
#include "battle_message.h"
#include "data/battle/battle_data.h"
#include "data/battle/anim_data.h"
#include "data/battle/ai_data.h"

extern void AnimTask_AcidArmor(u8 taskId);
extern void AnimTask_AirCutterProjectile(u8 taskId);
extern void AnimTask_AllocBackupPalBuffer(u8 taskId);
extern void AnimTask_AlphaFadeIn(u8 taskId);
extern void AnimTask_AnimateGustTornadoPalette(u8 taskId);
extern void AnimTask_AttackerFadeFromInvisible(u8 taskId);
extern void AnimTask_AttackerFadeToInvisible(u8 taskId);
extern void AnimTask_AttackerPunchWithTrace(u8 taskId);
extern void AnimTask_AttackerStretchAndDisappear(u8 taskId);
extern void AnimTask_BarrageBall(u8 taskId);
extern void AnimTask_BlendBackground(u8 taskId);
extern void AnimTask_BlendBattleAnimPal(u8 taskId);
extern void AnimTask_BlendBattleAnimPalExclude(u8 taskId);
extern void AnimTask_BlendColorCycle(u8 taskId);
extern void AnimTask_BlendColorCycleByTag(u8 taskId);
extern void AnimTask_BlendColorCycleExclude(u8 taskId);
extern void AnimTask_BlendMonInAndOut(u8 task);
extern void AnimTask_BlendNonAttackerPalettes(u8 taskId);
extern void AnimTask_BlendPalInAndOutByTag(u8 taskId);
extern void AnimTask_BlendParticle(u8 taskId);
extern void AnimTask_CastformGfxChange(u8 taskId);
extern void AnimTask_Conversion2AlphaBlend(u8 taskId);
extern void AnimTask_ConversionAlphaBlend(u8 taskId);
extern void AnimTask_CopyPalFadedToUnfaded(u8 taskId);
extern void AnimTask_CopyPalUnfadedFromBackup(u8 taskId);
extern void AnimTask_CopyPalUnfadedToBackup(u8 taskId);
extern void AnimTask_CreateRaindrops(u8 taskId);
extern void AnimTask_CreateSmallSolarBeamOrbs(u8 taskId);
extern void AnimTask_CreateSpotlight(u8 taskId);
extern void AnimTask_CreateSurfWave(u8 taskId);
extern void AnimTask_CurseStretchingBlackBg(u8 taskId);
extern void AnimTask_CycleMagicalLeafPal(u8 taskId);
extern void AnimTask_DeepInhale(u8 taskId);
extern void AnimTask_DefenseCurlDeformMon(u8 taskId);
extern void AnimTask_DestinyBondWhiteShadow(u8 taskId);
extern void AnimTask_DigDownMovement(u8 taskId);
extern void AnimTask_DigUpMovement(u8 taskId);
extern void AnimTask_DoomDesireLightBeam(u8 taskId);
extern void AnimTask_DoubleTeam(u8 taskId);
extern void AnimTask_DragonDanceWaver(u8 taskId);
extern void AnimTask_DrawFallingWhiteLinesOnAttacker(u8 taskId);
extern void AnimTask_DrillPeckHitSplats(u8 taskId);
extern void AnimTask_ElectricBolt(u8 taskId);
extern void AnimTask_ElectricChargingParticles(u8 taskId);
extern void AnimTask_EruptionLaunchRocks(u8 taskId);
extern void AnimTask_ExtrasensoryDistortion(u8 taskId);
extern void AnimTask_ExtremeSpeedImpact(u8 taskId);
extern void AnimTask_ExtremeSpeedMonReappear(u8 taskId);
extern void AnimTask_FacadeColorBlend(u8 taskId);
extern void AnimTask_FadeScreenToWhite(u8 taskId);
extern void AnimTask_FakeOut(u8 taskId);
extern void AnimTask_FlailMovement(u8 taskId);
extern void AnimTask_Flash(u8 taskId);
extern void AnimTask_FlashAnimTagWithColor(u8 taskId);
extern void AnimTask_FlashHealthboxOnLevelUp(u8 taskId);
extern void AnimTask_FreeBackupPalBuffer(u8 taskId);
extern void AnimTask_FreeBaitGfx(u8 taskId);
extern void AnimTask_FreeBallGfx(u8 taskId);
extern void AnimTask_FreeHealthboxPalsForLevelUp(u8 taskId);
extern void AnimTask_FreeMusicNotesPals(u8 taskId);
extern void AnimTask_FrozenIceCube(u8 taskId);
extern void AnimTask_GetAttackerSide(u8 taskId);
extern void AnimTask_GetBattleTerrain(u8 taskId);
extern void AnimTask_GetBattlersFromArg(u8 taskId);
extern void AnimTask_GetFrustrationPowerLevel(u8 taskId);
extern void AnimTask_GetFuryCutterHitCount(u8 taskId);
extern void AnimTask_GetReturnPowerLevel(u8 taskId);
extern void AnimTask_GetRolloutCounter(u8 taskId);
extern void AnimTask_GetSeismicTossDamageLevel(u8 taskId);
extern void AnimTask_GetTargetIsAttackerPartner(u8 taskId);
extern void AnimTask_GetTargetSide(u8 taskId);
extern void AnimTask_GetTrappedMoveAnimId(u8 taskId);
extern void AnimTask_GetWeather(u8 taskId);
extern void AnimTask_GhostGetOut(u8 taskId);
extern void AnimTask_GlareEyeDots(u8 taskId);
extern void AnimTask_GrowAndGrayscale(u8 taskId);
extern void AnimTask_GrowAndShrink(u8 taskId);
extern void AnimTask_GrudgeFlames(u8 taskId);
extern void AnimTask_Hail(u8 taskId);
extern void AnimTask_HardwarePaletteFade(u8 taskId);
extern void AnimTask_HazeScrollingFog(u8 taskId);
extern void AnimTask_HeartsBackground(u8 taskId);
extern void AnimTask_HelpingHandAttackerMovement(u8 taskId);
extern void AnimTask_HorizontalShake(u8 taskId);
extern void AnimTask_ImprisonOrbs(u8 taskId);
extern void AnimTask_InitAttackerFadeFromInvisible(u8 taskId);
extern void AnimTask_InitMementoShadow(u8 taskId);
extern void AnimTask_InvertScreenColor(u8 taskId);
extern void AnimTask_IsAttackerBehindSubstitute(u8 taskId);
extern void AnimTask_IsBallBlockedByTrainerOrDodged(u8 taskId);
extern void AnimTask_IsContest(u8 taskId);
extern void AnimTask_IsFuryCutterHitRight(u8 taskId);
extern void AnimTask_IsHealingMove(u8 taskId);
extern void AnimTask_IsMonInvisible(u8 taskId);
extern void AnimTask_IsPowerOver99(u8 taskId);
extern void AnimTask_IsTargetPlayerSide(u8 taskId);
extern void AnimTask_IsTargetSameSide(u8 taskId);
extern void AnimTask_LeafBlade(u8 taskId);
extern void AnimTask_LoadBaitGfx(u8 taskId);
extern void AnimTask_LoadBallGfx(u8 taskId);
extern void AnimTask_LoadHealthboxPalsForLevelUp(u8 taskId);
extern void AnimTask_LoadMusicNotesPals(u8 taskId);
extern void AnimTask_LoadSandstormBackground(u8 taskId);
extern void AnimTask_MeditateStretchAttacker(u8 taskId);
extern void AnimTask_MementoHandleBg(u8 taskId);
extern void AnimTask_MetallicShine(u8 taskId);
extern void AnimTask_Minimize(u8 taskId);
extern void AnimTask_MistBallFog(u8 taskId);
extern void AnimTask_MonToSubstitute(u8 taskId);
extern void AnimTask_MoonlightEndFade(u8 taskId);
extern void AnimTask_MorningSunLightBeam(u8 taskId);
extern void AnimTask_MoveAttackerMementoShadow(u8 taskId);
extern void AnimTask_MoveHeatWaveTargets(u8 taskId);
extern void AnimTask_MoveSeismicTossBg(u8 taskId);
extern void AnimTask_MoveSkyUppercutBg(u8 taskId);
extern void AnimTask_MoveTargetMementoShadow(u8 taskId);
extern void AnimTask_MusicNotesClearRainbowBlend(u8 taskId);
extern void AnimTask_MusicNotesRainbowBlend(u8 taskId);
extern void AnimTask_NightShadeClone(u8 taskId);
extern void AnimTask_NightmareClone(u8 taskId);
extern void AnimTask_OdorSleuthMovement(u8 taskId);
extern void AnimTask_PainSplitMovement(u8 taskId);
extern void AnimTask_PositionFissureBgOnBattler(u8 taskId);
extern void AnimTask_RapinSpinMonElevation(u8 taskId);
extern void AnimTask_RemoveSpotlight(u8 taskId);
extern void AnimTask_RockMonBackAndForth(u8 taskId);
extern void AnimTask_RolePlaySilhouette(u8 taskId);
extern void AnimTask_Rollout(u8 taskId);
extern void AnimTask_RotateAuroraRingColors(u8 taskId);
extern void AnimTask_RotateMonSpriteToSide(u8 taskId);
extern void AnimTask_RotateMonToSideAndRestore(u8 taskId);
extern void AnimTask_SafariGetReaction(u8 taskId);
extern void AnimTask_SafariOrGhost_DecideAnimSides(u8 taskId);
extern void AnimTask_ScaleMonAndRestore(u8 taskId);
extern void AnimTask_ScaryFace(u8 taskId);
extern void AnimTask_SeismicTossBgAccelerateDownAtEnd(u8 taskId);
extern void AnimTask_SetAllNonAttackersInvisiblity(u8 taskId);
extern void AnimTask_SetAnimAttackerAndTargetForEffectAtk(u8 taskId);
extern void AnimTask_SetAnimAttackerAndTargetForEffectTgt(u8 taskId);
extern void AnimTask_SetAnimTargetToBattlerTarget(u8 taskId);
extern void AnimTask_SetAttackerInvisibleWaitForSignal(u8 taskId);
extern void AnimTask_SetCamouflageBlend(u8 taskId);
extern void AnimTask_SetGrayscaleOrOriginalPal(u8 taskId);
extern void AnimTask_SetPsychicBackground(u8 taskId);
extern void AnimTask_SetTargetToEffectBattler(u8 taskId);
extern void AnimTask_ShakeAndSinkMon(u8 taskId);
extern void AnimTask_ShakeBattleTerrain(u8 taskId);
extern void AnimTask_ShakeMon(u8 taskId);
extern void AnimTask_ShakeMon2(u8 taskId);
extern void AnimTask_ShakeMonInPlace(u8 taskId);
extern void AnimTask_ShakeTargetBasedOnMovePowerOrDmg(u8 taskId);
extern void AnimTask_ShakeTargetInPattern(u8 taskId);
extern void AnimTask_ShockWaveLightning(u8 taskId);
extern void AnimTask_ShockWaveProgressingBolt(u8 taskId);
extern void AnimTask_ShrinkTargetCopy(u8 taskId);
extern void AnimTask_SketchDrawMon(u8 taskId);
extern void AnimTask_SkillSwap(u8 taskId);
extern void AnimTask_SkullBashPosition(u8 taskId);
extern void AnimTask_SlackOffSquish(u8 taskId);
extern void AnimTask_SlideMonForFocusBand(u8 taskId);
extern void AnimTask_SlideOffScreen(u8 taskId);
extern void AnimTask_SmellingSaltsSquish(u8 taskId);
extern void AnimTask_SmokescreenImpact(u8 taskId);
extern void AnimTask_SnatchOpposingMonMove(u8 taskId);
extern void AnimTask_SnatchPartnerMove(u8 taskId);
extern void AnimTask_SpeedDust(u8 taskId);
extern void AnimTask_SpitUpDeformMon(u8 taskId);
extern void AnimTask_SpiteTargetShadow(u8 taskId);
extern void AnimTask_Splash(u8 taskId);
extern void AnimTask_SporeDoubleBattle(u8 taskId);
extern void AnimTask_SquishAndSweatDroplets(u8 taskId);
extern void AnimTask_StartSinAnimTimer(u8 taskId);
extern void AnimTask_StartSlidingBg(u8 taskId);
extern void AnimTask_StatsChange(u8 taskId);
extern void AnimTask_StatusClearedEffect(u8 taskId);
extern void AnimTask_StockpileDeformMon(u8 taskId);
extern void AnimTask_StretchAttackerUp(u8 taskId);
extern void AnimTask_StretchTargetUp(u8 taskId);
extern void AnimTask_StrongFrustrationGrowAndShrink(u8 taskId);
extern void AnimTask_SubstituteFadeToInvisible(u8 taskId);
extern void AnimTask_SwallowDeformMon(u8 taskId);
extern void AnimTask_SwapMonSpriteToFromSubstitute(u8 taskId);
extern void AnimTask_SwayMon(u8 taskId);
extern void AnimTask_SwitchOutBallEffect(u8 taskId);
extern void AnimTask_SwitchOutShrinkMon(u8 taskId);
extern void AnimTask_TeeterDanceMovement(u8 taskId);
extern void AnimTask_Teleport(u8 taskId);
extern void AnimTask_ThrashMoveMonHorizontal(u8 taskId);
extern void AnimTask_ThrashMoveMonVertical(u8 taskId);
extern void AnimTask_ThrowBall(u8 taskId);
extern void AnimTask_ThrowBallSpecial(u8 taskId);
extern void AnimTask_TormentAttacker(u8 taskId);
extern void AnimTask_TraceMonBlended(u8 taskId);
extern void AnimTask_TransformMon(u8 taskId);
extern void AnimTask_TranslateMonElliptical(u8 taskId);
extern void AnimTask_TranslateMonEllipticalRespectSide(u8 taskId);
extern void AnimTask_TransparentCloneGrowAndShrink(u8 taskId);
extern void AnimTask_UproarDistortion(u8 taskId);
extern void AnimTask_VoltTackleAttackerReappear(u8 taskId);
extern void AnimTask_VoltTackleBolt(u8 taskId);
extern void AnimTask_WaterSport(u8 taskId);
extern void AnimTask_WaterSpoutLaunch(u8 taskId);
extern void AnimTask_WaterSpoutRain(u8 taskId);
extern void AnimTask_WindUpLunge(u8 taskId);
extern void AnimTask_Withdraw(u8 taskId);
extern void GetIsDoomDesireHitTurn(u8 taskId);
extern void SoundTask_AdjustPanningVar(u8 taskId);
extern void SoundTask_FireBlast(u8 taskId);
extern void SoundTask_LoopSEAdjustPanning(u8 taskId);
extern void SoundTask_PlayCryHighPitch(u8 taskId);
extern void SoundTask_PlayCryWithEcho(u8 taskId);
extern void SoundTask_PlayDoubleCry(u8 taskId);
extern void SoundTask_PlaySE1WithPanning(u8 taskId);
extern void SoundTask_PlaySE2WithPanning(u8 taskId);
extern void SoundTask_WaitForCry(u8 taskId);
extern const u16 gAbsorbDrainStringIds[];
extern const struct SpriteTemplate gAbsorptionOrbSpriteTemplate;
extern const struct SpriteTemplate gAcidPoisonBubbleSpriteTemplate;
extern const struct SpriteTemplate gAcidPoisonDropletSpriteTemplate;
extern const struct SpriteTemplate gAirCutterSliceSpriteTemplate;
extern const struct SpriteTemplate gAirWaveCrescentSpriteTemplate;
extern const struct SpriteTemplate gAncientPowerRockSpriteTemplate;
extern const struct SpriteTemplate gAngelSpriteTemplate;
extern const struct SpriteTemplate gAngerMarkSpriteTemplate;
extern const struct SpriteTemplate gArmThrustHandSpriteTemplate;
extern const struct SpriteTemplate gAromatherapyBigFlowerSpriteTemplate;
extern const struct SpriteTemplate gAromatherapySmallFlowerSpriteTemplate;
extern const struct SpriteTemplate gAssistPawprintSpriteTemplate;
extern const struct SpriteTemplate gAuroraBeamRingSpriteTemplate;
extern const u16 gBRNPreventionStringIds[];
extern const u16 gBallEscapeStringIds[];
extern const struct SpriteTemplate gBarrierWallSpriteTemplate;
extern const struct SpriteTemplate gBatonPassPokeballSpriteTemplate;
extern const struct SpriteTemplate gBellSpriteTemplate;
extern const struct SpriteTemplate gBellyDrumHandSpriteTemplate;
extern const struct SpriteTemplate gBentSpoonSpriteTemplate;
extern const u16 gBerryEffectStringIds[];
extern const struct SpriteTemplate gBlackBallSpriteTemplate;
extern const struct SpriteTemplate gBlackSmokeSpriteTemplate;
extern const struct SpriteTemplate gBlendThinRingExpandingSpriteTemplate;
extern const struct SpriteTemplate gBlizzardIceCrystalSpriteTemplate;
extern const struct SpriteTemplate gBlockXSpriteTemplate;
extern const struct SpriteTemplate gBonemerangSpriteTemplate;
extern const struct SpriteTemplate gBounceBallLandSpriteTemplate;
extern const struct SpriteTemplate gBounceBallShrinkSpriteTemplate;
extern const struct SpriteTemplate gBowMonSpriteTemplate;
extern const struct SpriteTemplate gBreathPuffSpriteTemplate;
extern const struct SpriteTemplate gBrickBreakWallShardSpriteTemplate;
extern const struct SpriteTemplate gBrickBreakWallSpriteTemplate;
extern const struct SpriteTemplate gBulletSeedSpriteTemplate;
extern const struct SpriteTemplate gBurnFlameSpriteTemplate;
extern const u16 gCaughtMonStringIds[];
extern const struct SpriteTemplate gClampJawSpriteTemplate;
extern const struct SpriteTemplate gClappingHand2SpriteTemplate;
extern const struct SpriteTemplate gClappingHandSpriteTemplate;
extern const struct SpriteTemplate gClawSlashSpriteTemplate;
extern const struct SpriteTemplate gCoinThrowSpriteTemplate;
extern const struct SpriteTemplate gComplexPaletteBlendSpriteTemplate;
extern const struct SpriteTemplate gConfuseRayBallBounceSpriteTemplate;
extern const struct SpriteTemplate gConfuseRayBallSpiralSpriteTemplate;
extern const struct SpriteTemplate gConfusionDuckSpriteTemplate;
extern const struct SpriteTemplate gConstrictBindingSpriteTemplate;
extern const struct SpriteTemplate gConversion2SpriteTemplate;
extern const struct SpriteTemplate gConversionSpriteTemplate;
extern const struct SpriteTemplate gCrossChopHandSpriteTemplate;
extern const struct SpriteTemplate gCrossImpactSpriteTemplate;
extern const struct SpriteTemplate gCurseGhostSpriteTemplate;
extern const struct SpriteTemplate gCurseNailSpriteTemplate;
extern const struct SpriteTemplate gCuttingSliceSpriteTemplate;
extern const struct SpriteTemplate gDevilSpriteTemplate;
extern const struct SpriteTemplate gDirtMoundSpriteTemplate;
extern const struct SpriteTemplate gDirtPlumeSpriteTemplate;
extern const struct SpriteTemplate gDiveBallSpriteTemplate;
extern const struct SpriteTemplate gDiveWaterSplashSpriteTemplate;
extern const struct SpriteTemplate gDizzyPunchDuckSpriteTemplate;
extern const u16 gDoubleBattleRecallStrings[1 << (MAX_BATTLERS_COUNT / 2)];
extern const struct SpriteTemplate gDragonBreathFireSpriteTemplate;
extern const struct SpriteTemplate gDragonDanceOrbSpriteTemplate;
extern const struct SpriteTemplate gDragonRageFirePlumeSpriteTemplate;
extern const struct SpriteTemplate gDragonRageFireSpitSpriteTemplate;
extern const struct SpriteTemplate gEclipsingOrbSpriteTemplate;
extern const struct SpriteTemplate gEggThrowSpriteTemplate;
extern const struct SpriteTemplate gElectricPuffSpriteTemplate;
extern const struct SpriteTemplate gElectricitySpriteTemplate;
extern const struct SpriteTemplate gEllipticalGustSpriteTemplate;
extern const struct SpriteTemplate gEmberFlareSpriteTemplate;
extern const struct SpriteTemplate gEmberSpriteTemplate;
extern const struct SpriteTemplate gEndureEnergySpriteTemplate;
extern const struct SpriteTemplate gEruptionFallingRockSpriteTemplate;
extern const struct SpriteTemplate gExplosionSpriteTemplate;
extern const struct SpriteTemplate gEyeSparkleSpriteTemplate;
extern const struct SpriteTemplate gFallingCoinSpriteTemplate;
extern const struct SpriteTemplate gFallingFeatherSpriteTemplate;
extern const struct SpriteTemplate gFallingRockSpriteTemplate;
extern const struct SpriteTemplate gFalseSwipePositionedSliceSpriteTemplate;
extern const struct SpriteTemplate gFalseSwipeSliceSpriteTemplate;
extern const struct SpriteTemplate gFangSpriteTemplate;
extern const struct SpriteTemplate gFastFlyingMusicNotesSpriteTemplate;
extern const u16 gFellAsleepStringIds[];
extern const struct SpriteTemplate gFireBlastCrossSpriteTemplate;
extern const struct SpriteTemplate gFireBlastRingSpriteTemplate;
extern const struct SpriteTemplate gFirePlumeSpriteTemplate;
extern const struct SpriteTemplate gFireSpinSpriteTemplate;
extern const struct SpriteTemplate gFireSpiralInwardSpriteTemplate;
extern const struct SpriteTemplate gFireSpiralOutwardSpriteTemplate;
extern const struct SpriteTemplate gFireSpreadSpriteTemplate;
extern const u16 gFirstTurnOfTwoStringIds[];
extern const struct SpriteTemplate gFistFootRandomPosSpriteTemplate;
extern const struct SpriteTemplate gFistFootSpriteTemplate;
extern const struct SpriteTemplate gFlamethrowerFlameSpriteTemplate;
extern const u16 gFlashFireStringIds[];
extern const struct SpriteTemplate gFlatterConfettiSpriteTemplate;
extern const struct SpriteTemplate gFlatterSpotlightSpriteTemplate;
extern const struct SpriteTemplate gFlyBallAttackSpriteTemplate;
extern const struct SpriteTemplate gFlyBallUpSpriteTemplate;
extern const struct SpriteTemplate gFlyingSandCrescentSpriteTemplate;
extern const u16 gFocusEnergyUsedStringIds[];
extern const struct SpriteTemplate gFocusPunchFistSpriteTemplate;
extern const struct SpriteTemplate gFollowMeFingerSpriteTemplate;
extern const struct SpriteTemplate gForesightMagnifyingGlassSpriteTemplate;
extern const struct SpriteTemplate gFrenzyPlantRootSpriteTemplate;
extern const struct SpriteTemplate gFurySwipesSpriteTemplate;
extern const u16 gFutureMoveUsedStringIds[];
extern const struct SpriteTemplate gGoldRingSpriteTemplate;
extern const u16 gGotBurnedStringIds[];
extern const u16 gGotDefrostedStringIds[];
extern const u16 gGotFrozenStringIds[];
extern const u16 gGotParalyzedStringIds[];
extern const u16 gGotPoisonedStringIds[];
extern const struct SpriteTemplate gGrantingStarsSpriteTemplate;
extern const struct SpriteTemplate gGreenStarSpriteTemplate;
extern const struct SpriteTemplate gGrowingChargeOrbSpriteTemplate;
extern const struct SpriteTemplate gGrowingShockWaveOrbSpriteTemplate;
extern const struct SpriteTemplate gGuardRingSpriteTemplate;
extern const struct SpriteTemplate gGuillotineSpriteTemplate;
extern const struct SpriteTemplate gGustToTargetSpriteTemplate;
extern const struct SpriteTemplate gHandleInvertHitSplatSpriteTemplate;
extern const struct SpriteTemplate gHealBellMusicNoteSpriteTemplate;
extern const struct SpriteTemplate gHealingBlueStarSpriteTemplate;
extern const struct SpriteTemplate gHelpingHandClapSpriteTemplate;
extern const struct SpriteTemplate gHiddenPowerOrbScatterSpriteTemplate;
extern const struct SpriteTemplate gHiddenPowerOrbSpriteTemplate;
extern const struct SpriteTemplate gHorizontalLungeSpriteTemplate;
extern const struct SpriteTemplate gHornHitSpriteTemplate;
extern const struct SpriteTemplate gHydroCannonBeamSpriteTemplate;
extern const struct SpriteTemplate gHydroCannonChargeSpriteTemplate;
extern const struct SpriteTemplate gHydroPumpOrbSpriteTemplate;
extern const struct SpriteTemplate gHyperBeamOrbSpriteTemplate;
extern const struct SpriteTemplate gHyperVoiceRingSpriteTemplate;
extern const struct SpriteTemplate gIceBallChunkSpriteTemplate;
extern const struct SpriteTemplate gIceBallImpactShardSpriteTemplate;
extern const struct SpriteTemplate gIceBeamInnerCrystalSpriteTemplate;
extern const struct SpriteTemplate gIceBeamOuterCrystalSpriteTemplate;
extern const struct SpriteTemplate gIceCrystalHitLargeSpriteTemplate;
extern const struct SpriteTemplate gIceCrystalHitSmallSpriteTemplate;
extern const struct SpriteTemplate gIceCrystalSpiralInwardLarge;
extern const struct SpriteTemplate gIceCrystalSpiralInwardSmall;
extern const struct SpriteTemplate gIceGroundSpikeSpriteTemplate;
extern const struct SpriteTemplate gIcicleSpearSpriteTemplate;
extern const struct SpriteTemplate gIngrainOrbSpriteTemplate;
extern const struct SpriteTemplate gIngrainRootSpriteTemplate;
extern const u16 gInobedientStringIds[];
extern const struct SpriteTemplate gItemStealSpriteTemplate;
extern const u16 gItemSwapStringIds[];
extern const struct SpriteTemplate gJaggedMusicNoteSpriteTemplate;
extern const struct SpriteTemplate gJumpKickSpriteTemplate;
extern const u16 gKOFailedStringIds[];
extern const struct SpriteTemplate gKarateChopSpriteTemplate;
extern const struct SpriteTemplate gKinesisZapEnergySpriteTemplate;
extern const struct SpriteTemplate gKnockOffItemSpriteTemplate;
extern const struct SpriteTemplate gKnockOffStrikeSpriteTemplate;
extern const struct SpriteTemplate gLargeFlameScatterSpriteTemplate;
extern const struct SpriteTemplate gLargeFlameSpriteTemplate;
extern const struct SpriteTemplate gLeechLifeNeedleSpriteTemplate;
extern const struct SpriteTemplate gLeechSeedSpriteTemplate;
extern const u16 gLeechSeedStringIds[];
extern const struct SpriteTemplate gLeerSpriteTemplate;
extern const struct SpriteTemplate gLetterZSpriteTemplate;
extern const struct SpriteTemplate gLickSpriteTemplate;
extern const struct SpriteTemplate gLightScreenWallSpriteTemplate;
extern const struct SpriteTemplate gLightningSpriteTemplate;
extern const struct SpriteTemplate gLinearStingerSpriteTemplate;
extern const struct SpriteTemplate gLockOnMoveTargetSpriteTemplate;
extern const struct SpriteTemplate gLockOnTargetSpriteTemplate;
extern const struct SpriteTemplate gLusterPurgeCircleSpriteTemplate;
extern const struct SpriteTemplate gMagentaHeartSpriteTemplate;
extern const struct SpriteTemplate gMagicCoatWallSpriteTemplate;
extern const struct SpriteTemplate gMeanLookEyeSpriteTemplate;
extern const struct SpriteTemplate gMegaPunchKickSpriteTemplate;
extern const struct SpriteTemplate gMegahornHornSpriteTemplate;
extern const struct SpriteTemplate gMetalSoundSpriteTemplate;
extern const struct SpriteTemplate gMeteorMashStarSpriteTemplate;
extern const struct SpriteTemplate gMetronomeFingerSpriteTemplate;
extern const struct SpriteTemplate gMilkBottleSpriteTemplate;
extern const struct SpriteTemplate gMimicOrbSpriteTemplate;
extern const struct SpriteTemplate gMirrorCoatWallSpriteTemplate;
extern const struct SpriteTemplate gMistBallSpriteTemplate;
extern const struct SpriteTemplate gMistCloudSpriteTemplate;
extern const u16 gMistUsedStringIds[];
extern const struct SpriteTemplate gMonEdgeHitSplatSpriteTemplate;
extern const struct SpriteTemplate gMoonSpriteTemplate;
extern const struct SpriteTemplate gMoonlightSparkleSpriteTemplate;
extern const u16 gMoveWeatherChangeStringIds[];
extern const struct SpriteTemplate gMovementWavesSpriteTemplate;
extern const struct SpriteTemplate gMudShotOrbSpriteTemplate;
extern const struct SpriteTemplate gMudSlapMudSpriteTemplate;
extern const struct SpriteTemplate gMudsportMudSpriteTemplate;
extern const struct SpriteTemplate gNeedleArmSpikeSpriteTemplate;
extern const struct SpriteTemplate gNightmareDevilSpriteTemplate;
extern const u16 gNoEscapeStringIds[];
extern u8 gNumSafariBalls;
extern const struct SpriteTemplate gOctazookaBallSpriteTemplate;
extern const struct SpriteTemplate gOctazookaSmokeSpriteTemplate;
extern const struct SpriteTemplate gOpeningEyeSpriteTemplate;
extern const struct SpriteTemplate gOutrageFlameSpriteTemplate;
extern const struct SpriteTemplate gOverheatFlameSpriteTemplate;
extern const u16 gPRLZPreventionStringIds[];
extern const u16 gPSNPreventionStringIds[];
extern const struct SpriteTemplate gPainSplitProjectileSpriteTemplate;
extern const u16 gPartyStatusHealStringIds[];
extern const struct SpriteTemplate gPencilSpriteTemplate;
extern const struct SpriteTemplate gPerishSongMusicNote2SpriteTemplate;
extern const struct SpriteTemplate gPerishSongMusicNoteSpriteTemplate;
extern const struct SpriteTemplate gPersistHitSplatSpriteTemplate;
extern const struct SpriteTemplate gPetalDanceBigFlowerSpriteTemplate;
extern const struct SpriteTemplate gPetalDanceSmallFlowerSpriteTemplate;
extern const struct SpriteTemplate gPinMissileSpriteTemplate;
extern const struct SpriteTemplate gPinkHeartSpriteTemplate;
extern const struct SpriteTemplate gPoisonBubbleSpriteTemplate;
extern const struct SpriteTemplate gPoisonGasCloudSpriteTemplate;
extern const struct SpriteTemplate gPoisonPowderParticleSpriteTemplate;
extern const struct SpriteTemplate gPowderSnowSnowballSpriteTemplate;
extern const struct SpriteTemplate gPowerAbsorptionOrbSpriteTemplate;
extern const struct SpriteTemplate gPresentHealParticleSpriteTemplate;
extern const struct SpriteTemplate gPresentSpriteTemplate;
extern const u16 gProtectLikeUsedStringIds[];
extern const struct SpriteTemplate gProtectSpriteTemplate;
extern const struct SpriteTemplate gPsychUpSpiralSpriteTemplate;
extern const struct SpriteTemplate gPsychoBoostOrbSpriteTemplate;
extern const struct SpriteTemplate gPsywaveRingSpriteTemplate;
extern const struct SpriteTemplate gQuestionMarkSpriteTemplate;
extern const u16 gRainContinuesStringIds[];
extern const struct SpriteTemplate gRandomPosHitSplatSpriteTemplate;
extern const struct SpriteTemplate gRapidSpinSpriteTemplate;
extern const struct SpriteTemplate gRazorLeafCutterSpriteTemplate;
extern const struct SpriteTemplate gRazorLeafParticleSpriteTemplate;
extern const struct SpriteTemplate gRazorWindTornadoSpriteTemplate;
extern const struct SpriteTemplate gRecycleSpriteTemplate;
extern const struct SpriteTemplate gRedHeartBurstSpriteTemplate;
extern const struct SpriteTemplate gRedHeartProjectileSpriteTemplate;
extern const struct SpriteTemplate gRedHeartRisingSpriteTemplate;
extern const struct SpriteTemplate gRedXSpriteTemplate;
extern const u16 gReflectLightScreenSafeguardStringIds[];
extern const struct SpriteTemplate gReflectSparkleSpriteTemplate;
extern const struct SpriteTemplate gReflectWallSpriteTemplate;
extern const u16 gRestUsedStringIds[];
extern const struct SpriteTemplate gRevengeBigScratchSpriteTemplate;
extern const struct SpriteTemplate gRevengeSmallScratchSpriteTemplate;
extern const struct SpriteTemplate gReversalOrbSpriteTemplate;
extern const struct SpriteTemplate gRoarNoiseLineSpriteTemplate;
extern const struct SpriteTemplate gRockBlastRockSpriteTemplate;
extern const struct SpriteTemplate gRockFragmentSpriteTemplate;
extern const struct SpriteTemplate gRockScatterSpriteTemplate;
extern const struct SpriteTemplate gRockTombRockSpriteTemplate;
extern const struct SpriteTemplate gSafariBaitSpriteTemplate;
extern const u16 gSafariReactionStringIds[NUM_SAFARI_REACTIONS];
extern const struct SpriteTemplate gSafariRockTemplate;
extern const struct SpriteTemplate gSandAttackDirtSpriteTemplate;
extern const u16 gSandstormHailContinuesStringIds[];
extern const u16 gSandstormHailDmgStringIds[];
extern const u16 gSandstormHailEndStringIds[];
extern const struct SpriteTemplate gScratchSpriteTemplate;
extern const struct SpriteTemplate gScreechRingSpriteTemplate;
extern const struct SpriteTemplate gShadowBallSpriteTemplate;
extern const struct SpriteTemplate gShakeMonOrTerrainSpriteTemplate;
extern const struct SpriteTemplate gSharpTeethSpriteTemplate;
extern const struct SpriteTemplate gSharpenSphereSpriteTemplate;
extern const struct SpriteTemplate gSignalBeamGreenOrbSpriteTemplate;
extern const struct SpriteTemplate gSignalBeamRedOrbSpriteTemplate;
extern const struct SpriteTemplate gSilverWindBigSparkSpriteTemplate;
extern const struct SpriteTemplate gSilverWindMediumSparkSpriteTemplate;
extern const struct SpriteTemplate gSilverWindSmallSparkSpriteTemplate;
extern const struct SpriteTemplate gSimplePaletteBlendSpriteTemplate;
extern const struct SpriteTemplate gSkyAttackBirdSpriteTemplate;
extern const struct SpriteTemplate gSlamHitSpriteTemplate;
extern const struct SpriteTemplate gSlashSliceSpriteTemplate;
extern const struct SpriteTemplate gSleepLetterZSpriteTemplate;
extern const struct SpriteTemplate gSleepPowderParticleSpriteTemplate;
extern const struct SpriteTemplate gSlideMonToOffsetAndBackSpriteTemplate;
extern const struct SpriteTemplate gSlideMonToOffsetSpriteTemplate;
extern const struct SpriteTemplate gSlideMonToOriginalPosSpriteTemplate;
extern const struct SpriteTemplate gSlidingKickSpriteTemplate;
extern const struct SpriteTemplate gSlowFlyingMusicNotesSpriteTemplate;
extern const struct SpriteTemplate gSludgeBombHitParticleSpriteTemplate;
extern const struct SpriteTemplate gSludgeProjectileSpriteTemplate;
extern const struct SpriteTemplate gSmallBubblePairSpriteTemplate;
extern const struct SpriteTemplate gSmallDriftingBubblesSpriteTemplate;
extern const struct SpriteTemplate gSmellingSaltExclamationSpriteTemplate;
extern const struct SpriteTemplate gSmellingSaltsHandSpriteTemplate;
extern const struct SpriteTemplate gSmogCloudSpriteTemplate;
extern const struct SpriteTemplate gSmokeBallEscapeCloudSpriteTemplate;
extern const struct SpriteTemplate gSnoreZSpriteTemplate;
extern const struct SpriteTemplate gSoftBoiledEggSpriteTemplate;
extern const struct SpriteTemplate gSolarBeamBigOrbSpriteTemplate;
extern const struct SpriteTemplate gSonicBoomSpriteTemplate;
extern const struct SpriteTemplate gSparkElectricityFlashingSpriteTemplate;
extern const struct SpriteTemplate gSparkElectricitySpriteTemplate;
extern const struct SpriteTemplate gSparklingStarsSpriteTemplate;
extern const struct SpriteTemplate gSpecialScreenSparkleSpriteTemplate;
extern const struct SpriteTemplate gSpiderWebSpriteTemplate;
extern const struct SpriteTemplate gSpikesSpriteTemplate;
extern const struct SpriteTemplate gSpinningBoneSpriteTemplate;
extern const struct SpriteTemplate gSpinningHandOrFootSpriteTemplate;
extern const struct SpriteTemplate gSpinningSparkleSpriteTemplate;
extern const struct SpriteTemplate gSpitUpOrbSpriteTemplate;
extern const struct SpriteTemplate gSporeParticleSpriteTemplate;
extern const u16 gSportsUsedStringIds[];
extern const struct SpriteTemplate gSpotlightSpriteTemplate;
extern const struct SpriteTemplate gSprayWaterDropletSpriteTemplate;
extern const u16 gStatDownStringIds[];
extern const u16 gStatUpStringIds[];
extern const struct SpriteTemplate gStockpileAbsorptionOrbSpriteTemplate;
extern const u16 gStockpileUsedStringIds[];
extern const struct SpriteTemplate gStompFootSpriteTemplate;
extern const struct SpriteTemplate gStringWrapSpriteTemplate;
extern const struct SpriteTemplate gStunSporeParticleSpriteTemplate;
extern const u16 gSubstituteUsedStringIds[];
extern const struct SpriteTemplate gSunlightRaySpriteTemplate;
extern const struct SpriteTemplate gSuperFangSpriteTemplate;
extern const struct SpriteTemplate gSuperpowerFireballSpriteTemplate;
extern const struct SpriteTemplate gSuperpowerOrbSpriteTemplate;
extern const struct SpriteTemplate gSuperpowerRockSpriteTemplate;
extern const struct SpriteTemplate gSupersonicRingSpriteTemplate;
extern const struct SpriteTemplate gSwallowBlueOrbSpriteTemplate;
extern const u16 gSwallowFailStringIds[];
extern const struct SpriteTemplate gSweetScentPetalSpriteTemplate;
extern const struct SpriteTemplate gSwiftStarSpriteTemplate;
extern const struct SpriteTemplate gSwirlingDirtSpriteTemplate;
extern const struct SpriteTemplate gSwirlingSnowballSpriteTemplate;
extern const struct SpriteTemplate gSwordsDanceBladeSpriteTemplate;
extern const struct SpriteTemplate gTailGlowOrbSpriteTemplate;
extern const struct SpriteTemplate gTauntFingerSpriteTemplate;
extern const struct SpriteTemplate gTealAlertSpriteTemplate;
extern const struct SpriteTemplate gTearDropSpriteTemplate;
extern const struct SpriteTemplate gThinRingExpandingSpriteTemplate;
extern const struct SpriteTemplate gThinRingShrinkingSpriteTemplate;
extern const struct SpriteTemplate gThunderWaveSpriteTemplate;
extern const struct SpriteTemplate gThunderboltOrbSpriteTemplate;
extern const struct SpriteTemplate gToxicBubbleSpriteTemplate;
extern const u16 gTrainerItemCuredStatusStringIds[];
extern const u16 gTransformUsedStringIds[];
extern const struct SpriteTemplate gTriAttackTriangleSpriteTemplate;
extern const struct SpriteTemplate gTrickBagSpriteTemplate;
extern const struct SpriteTemplate gTwisterLeafSpriteTemplate;
extern const struct SpriteTemplate gTwisterRockSpriteTemplate;
extern const u16 gUproarAwakeStringIds[];
extern const u16 gUproarOverTurnStringIds[];
extern const struct SpriteTemplate gUproarRingSpriteTemplate;
extern const struct SpriteTemplate gVerticalDipSpriteTemplate;
extern const struct SpriteTemplate gViceGripSpriteTemplate;
extern const struct SpriteTemplate gVineWhipSpriteTemplate;
extern const struct SpriteTemplate gVoltTackleOrbSlideSpriteTemplate;
extern const struct SpriteTemplate gWaterBubbleProjectileSpriteTemplate;
extern const struct SpriteTemplate gWaterBubbleSpriteTemplate;
extern const struct SpriteTemplate gWaterGunDropletSpriteTemplate;
extern const struct SpriteTemplate gWaterGunProjectileSpriteTemplate;
extern const struct SpriteTemplate gWaterPulseBubbleSpriteTemplate;
extern const struct SpriteTemplate gWaterPulseRingSpriteTemplate;
extern const struct SpriteTemplate gWavyMusicNotesSpriteTemplate;
extern const struct SpriteTemplate gWeakFrustrationAngerMarkSpriteTemplate;
extern const struct SpriteTemplate gWeatherBallFireDownSpriteTemplate;
extern const struct SpriteTemplate gWeatherBallIceDownSpriteTemplate;
extern const struct SpriteTemplate gWeatherBallNormalDownSpriteTemplate;
extern const struct SpriteTemplate gWeatherBallRockDownSpriteTemplate;
extern const struct SpriteTemplate gWeatherBallUpSpriteTemplate;
extern const struct SpriteTemplate gWeatherBallWaterDownSpriteTemplate;
extern const u16 gWeatherStartsStringIds[];
extern const struct SpriteTemplate gWebThreadSpriteTemplate;
extern const struct SpriteTemplate gWhirlpoolSpriteTemplate;
extern const struct SpriteTemplate gWhirlwindLineSpriteTemplate;
extern const struct SpriteTemplate gWhiteHaloSpriteTemplate;
extern const struct SpriteTemplate gWillOWispFireSpriteTemplate;
extern const struct SpriteTemplate gWillOWispOrbSpriteTemplate;
extern const u16 gWokeUpStringIds[];
extern const u16 gWrappedStringIds[];
extern const struct SpriteTemplate gYawnCloudSpriteTemplate;
extern const struct SpriteTemplate gZapCannonBallSpriteTemplate;
extern const struct SpriteTemplate gZapCannonSparkSpriteTemplate;

const void *const gNativeBattlePtrs[] = {
    &gCurrentMove,
    BattleScript_HitFromAtkCanceler,
    &gHitMarker,
    (void *)((u8 *)&gBattleScripting + 14),
    BattleScript_PrintMoveMissed,
    NULL,
    (void *)((u8 *)&gBattleScripting + 20),
    &gMoveResultFlags,
    BattleScript_MoveEnd,
    BattleScript_ButItFailed,
    BattleScript_AlreadyAsleep,
    BattleScript_CantMakeAsleep,
    BattleScript_SafeguardProtected,
    (void *)((u8 *)gBattleCommunication + 3),
    gUproarAwakeStringIds,
    BattleScript_EffectHit,
    BattleScript_AbsorbLiquidOoze,
    (void *)((u8 *)gBattleCommunication + 5),
    BattleScript_AbsorbUpdateHp,
    BattleScript_AbsorbTryFainting,
    gAbsorbDrainStringIds,
    BattleScript_ExplosionDoAnimStartLoop,
    BattleScript_PreserveMissedBitDoMoveAnim,
    BattleScript_ExplosionLoop,
    BattleScript_ExplosionMissed,
    BattleScript_DreamEaterNoEffect,
    BattleScript_DreamEaterWorked,
    BattleScript_WasntAffected,
    BattleScript_DreamEaterTryFaintEnd,
    (void *)((u8 *)&gBattleScripting + 26),
    BattleScript_EffectStatUp,
    BattleScript_StatUpEnd,
    BattleScript_StatUpAttackAnim,
    BattleScript_StatUpPrintString,
    (void *)((u8 *)&gBattleScripting + 16),
    gStatUpStringIds,
    BattleScript_EffectStatDown,
    BattleScript_ButItFailedAtkStringPpReduce,
    BattleScript_StatDownEnd,
    BattleScript_StatDownDoAnim,
    BattleScript_StatDownPrintString,
    gStatDownStringIds,
    BattleScript_EffectRampage2,
    BattleScript_HitFromCritCalc,
    BattleScript_AbilityPreventsPhasingOut,
    BattleScript_PrintMonIsRooted,
    BattleScript_MoveMissedPause,
    (void *)((u8 *)&gBattleScripting + 22),
    BattleScript_MultiHitEnd,
    BattleScript_MultiHitPrintStrings,
    &gChosenMove,
    BattleScript_DoMultiHit,
    BattleScript_MultiHitNoMoreHits,
    (void *)((u8 *)&gBattleScripting + 12),
    BattleScript_MultiHitLoop,
    gBattleTextBuff1,
    (void *)((u8 *)&gBattleScripting + 8),
    BattleScript_AlreadyAtFullHp,
    BattleScript_ImmunityProtected,
    BattleScript_AlreadyPoisoned,
    BattleScript_NotAffected,
    &gEffectBattler,
    &gBattlerTarget,
    BattleScript_PSNPrevention,
    BattleScript_PrintReflectLightScreenSafeguardString,
    BattleScript_RestIsAlreadyAsleep,
    BattleScript_RestCantSleep,
    gRestUsedStringIds,
    BattleScript_PresentHealTarget,
    BattleScript_HitFromAtkAnimation,
    BattleScript_KOFail,
    gKOFailedStringIds,
    BattleScript_TwoTurnMovesSecondTurn,
    (void *)((u8 *)&gBattleScripting + 15),
    BattleScriptFirstChargingTurn,
    (void *)((u8 *)&gBattleScripting + 24),
    BattleScript_HitFromAccCheck,
    gFirstTurnOfTwoStringIds,
    &gBattleMoveDamage,
    (void *)((u8 *)&gBattleMoveDamage + 1),
    (void *)((u8 *)&gBattleMoveDamage + 2),
    (void *)((u8 *)&gBattleMoveDamage + 3),
    BattleScript_DoWrapEffect,
    BattleScript_MoveMissedDoDamage,
    BattleScript_HitFromAtkString,
    gMistUsedStringIds,
    gFocusEnergyUsedStringIds,
    BattleScript_OwnTempoPrevents,
    BattleScript_AlreadyConfused,
    gTransformUsedStringIds,
    gReflectLightScreenSafeguardStringIds,
    BattleScript_LimberProtected,
    BattleScript_AlreadyParalyzed,
    BattleScript_PRLZPrevention,
    BattleScript_AlreadyHasSubstitute,
    BattleScript_SubstituteAnim,
    BattleScript_SubstituteString,
    gSubstituteUsedStringIds,
    BattleScript_RageMiss,
    (void *)((u8 *)&gBattleScripting + 25),
    BattleScript_DoLeechSeed,
    gLeechSeedStringIds,
    (void *)((u8 *)&gBattleScripting + 0),
    BattleScript_SnoreIsAsleep,
    BattleScript_DoSnore,
    BattleScript_SleepTalkIsAsleep,
    BattleScript_SleepTalkUsingMove,
    gPartyStatusHealStringIds,
    BattleScript_PartyHealEnd,
    BattleScript_CheckHealBellMon2Unaffected,
    (void *)((u8 *)&gBattleScripting + 18),
    (void *)((u8 *)&gBattleScripting + 19),
    BattleScript_TripleKickEnd,
    BattleScript_TripleKickNoMoreHits,
    BattleScript_DoTripleKickAttack,
    &gDynamicBasePower,
    BattleScript_TripleKickPrintStrings,
    BattleScript_TripleKickLoop,
    BattleScript_NightmareWorked,
    BattleScript_EffectStatUpAfterAtkCanceler,
    BattleScript_GhostCurse,
    BattleScript_CurseTrySpeed,
    &gBattlerAttacker,
    BattleScript_CurseTryAttack,
    BattleScript_CurseTryDefense,
    BattleScript_CurseEnd,
    BattleScript_DoGhostCurse,
    gProtectLikeUsedStringIds,
    (void *)((u8 *)&gBattleScripting + 23),
    BattleScript_PerishSongNotAffected,
    &gBattlersCount,
    BattleScript_PerishSongLoop,
    BattleScript_PerishSongLoopIncrement,
    BattleScript_MoveWeatherChange,
    BattleScript_RolloutCheckAccuracy,
    BattleScript_RolloutHit,
    BattleScript_MakeMoveMissed,
    BattleScript_SwaggerTryConfuse,
    BattleScript_FuryCutterHit,
    BattleScript_HitsAllWithUndergroundBonusLoop,
    gMoveWeatherChangeStringIds,
    BattleScript_WeatherFormChanges,
    BattleScript_SkullBashEnd,
    BattleScript_FlinchEffect,
    BattleScript_HitsAllNoUndergroundBonus,
    BattleScript_DoHitAllWithUndergroundBonus,
    BattleScript_HitAllWithUndergroundBonusMissed,
    gFutureMoveUsedStringIds,
    BattleScript_SolarBeamDecideTurn,
    &gBattleWeather,
    BattleScript_SolarBeamOnFirstTurn,
    &gBattleTypeFlags,
    gBattleCommunication,
    BattleScript_PrintAbilityMadeIneffective,
    &gBattleOutcome,
    BattleScript_BeatUpEnd,
    &gCritMultiplier,
    BattleScript_BeatUpAttack,
    BattleScript_BeatUpLoop,
    BattleScript_SecondTurnSemiInvulnerable,
    BattleScript_FirstTurnFly,
    BattleScript_FirstTurnDive,
    BattleScript_FirstTurnBounce,
    BattleScript_FirstTurnSemiInvulnerable,
    BattleScript_SemiInvulnerableTryHit,
    BattleScript_SemiInvulnerableMiss,
    BattleScript_DefenseCurlDoStatUpAnim,
    BattleScript_StatUpDoAnim,
    BattleScript_UproarHit,
    gStockpileUsedStringIds,
    (void *)((u8 *)gBattleCommunication + 6),
    BattleScript_SpitUpFailProtect,
    BattleScript_SpitUpFail,
    BattleScript_SwallowFail,
    gSwallowFailStringIds,
    BattleScript_FlatterTryConfuse,
    BattleScript_AlreadyBurned,
    BattleScript_WaterVeilPrevents,
    BattleScript_BRNPrevention,
    BattleScript_MementoTargetProtect,
    BattleScript_EffectMementoPrintNoEffect,
    (void *)((u8 *)&gBattleScripting + 27),
    BattleScript_EffectMementoTrySpAtk,
    BattleScript_EffectMementoTryFaint,
    BattleScript_MementoTargetProtectEnd,
    BattleScript_FacadeDoubleDmg,
    BattleScript_SmellingsaltDoubleDmg,
    gItemSwapStringIds,
    BattleScript_ButItFailedPpReduce,
    BattleScript_BrickBreakAnim,
    BattleScript_BrickBreakDoHit,
    BattleScript_PrintBankAbilityMadeIneffective,
    (void *)((u8 *)&gBattleScripting + 21),
    &gHpDealt,
    BattleScript_TeeterDanceLoopIncrement,
    BattleScript_TeeterDanceOwnTempoPrevents,
    BattleScript_TeeterDanceSubstitutePrevents,
    BattleScript_TeeterDanceAlreadyConfused,
    BattleScript_TeeterDanceMissed,
    BattleScript_TeeterDanceSafeguardProtected,
    BattleScript_TeeterDanceLoop,
    gSportsUsedStringIds,
    BattleScript_TickleDoMoveAnim,
    BattleScript_CantLowerMultipleStats,
    BattleScript_TickleTryLowerDef,
    BattleScript_TickleEnd,
    BattleScript_CosmicPowerDoMoveAnim,
    BattleScript_CantRaiseMultipleStats,
    BattleScript_CosmicPowerTrySpDef,
    BattleScript_CosmicPowerEnd,
    BattleScript_BulkUpDoMoveAnim,
    BattleScript_BulkUpTryDef,
    BattleScript_BulkUpEnd,
    BattleScript_CalmMindDoMoveAnim,
    BattleScript_CalmMindTrySpDef,
    BattleScript_CalmMindEnd,
    BattleScript_DragonDanceDoMoveAnim,
    BattleScript_DragonDanceTrySpeed,
    BattleScript_DragonDanceEnd,
    (void *)((u8 *)&gBattleScripting + 28),
    BattleScript_LinkHandleFaintedMonMultiple,
    BattleScript_FaintedMonEnd,
    BattleScript_FaintedMonTryChoose,
    (void *)((u8 *)gBattleCommunication + 1),
    BattleScript_FaintedMonSendOutNew,
    (void *)((u8 *)&gBattleScripting + 29),
    BattleScript_LinkHandleFaintedMonMultipleStart,
    BattleScript_LinkHandleFaintedMonMultipleEnd,
    &gBattlerFainted,
    BattleScript_LinkHandleFaintedMonLoop,
    BattleScript_LocalTrainerBattleWonGotMoney,
    BattleScript_BattleTowerLost,
    BattleScript_EReaderOrSecretBaseTrainerEnd,
    &gTrainerBattleOpponent_A,
    BattleScript_RivalBattleLost,
    BattleScript_LocalBattleLostEnd,
    BattleScript_LocalBattleLostPrintTrainersWinText,
    BattleScript_RivalBattleLostSkipMonRecall,
    BattleScript_LocalBattleLostPrintWhiteOut,
    BattleScript_BattleTowerLostLostSkipMonRecall,
    gDoubleBattleRecallStrings,
    BattleScript_BattleTowerLostLostSkipDouble,
    BattleScript_BattleTowerEtcTrainerBattleWonSkipText,
    BattleScript_LeftoverBirchString,
    gNoEscapeStringIds,
    BattleScript_PursuitSwitchDmgSetMultihit,
    BattleScript_PursuitSwitchDmgLoop,
    BattleScript_DoSwitchOut,
    BattleScript_PursuitDmgOnSwitchOut,
    BattleScript_PursuitDmgOnSwitchOutRet,
    (void *)((u8 *)&gBattleScripting + 30),
    BattleScript_LearnedNewMove,
    BattleScript_LearnMoveReturn,
    BattleScript_AskToLearnMove,
    (void *)((u8 *)&gBattleScripting + 31),
    BattleScript_ForgotAndLearnedNewMove,
    BattleScript_TryLearnMoveLoop,
    gRainContinuesStringIds,
    BattleScript_RainContinuesOrEndsEnd,
    gSandstormHailContinuesStringIds,
    gBattlerByTurnOrder,
    BattleScript_DamagingWeatherContinuesEnd,
    gSandstormHailDmgStringIds,
    BattleScript_WeatherDamageEndedBattle,
    BattleScript_DamagingWeatherLoop,
    gSandstormHailEndStringIds,
    gWeatherStartsStringIds,
    BattleScript_LeechSeedLiquidOoze,
    BattleScript_LeechSeedTurnPrintAndUpdateHp,
    BattleScript_MoveMissed,
    (void *)((u8 *)&gBattleScripting + 4),
    BattleScript_TrainerBattleForceOut,
    BattleScript_PrintHurtBySpikes,
    BattleScript_SpikesOnAttackerFainted,
    BattleScript_HandleFaintedMon,
    BattleScript_SpikesOnTargetFainted,
    BattleScript_SpikesOnFaintedBattlerFainted,
    BattleScript_AllStatsUpAtk,
    BattleScript_AllStatsUpRet,
    BattleScript_AllStatsUpDef,
    BattleScript_AllStatsUpSpeed,
    BattleScript_AllStatsUpSpAtk,
    BattleScript_AllStatsUpSpDef,
    BattleScript_CheckDoomDesireMiss,
    BattleScript_FutureAttackMiss,
    BattleScript_FutureAttackAnimate,
    BattleScript_FutureHitAnimDoomDesire,
    BattleScript_DoFutureAttackHit,
    BattleScript_FutureAttackEnd,
    BattleScript_WishButFullHp,
    BattleScript_AtkDefDownAtkFail,
    BattleScript_AtkDefDownDefFail,
    BattleScript_SAtkDown2End,
    gWokeUpStringIds,
    BattleScript_DoTurnDmgEnd,
    BattleScript_DoStatusTurnDmg,
    gGotDefrostedStringIds,
    gUproarOverTurnStringIds,
    BattleScript_MoveUsedIsConfusedRet,
    BattleScript_DoTurnDmg,
    gFellAsleepStringIds,
    gGotPoisonedStringIds,
    BattleScript_UpdateEffectStatusIconRet,
    gGotBurnedStringIds,
    gGotFrozenStringIds,
    gGotParalyzedStringIds,
    gWrappedStringIds,
    BattleScript_DoRecoil,
    BattleScript_RecoilEnd,
    BattleScript_WeatherFormChangesLoop,
    BattleScript_DoCastformChangeAnim,
    BattleScript_DoIntimidateActivationAnim,
    BattleScript_IntimidateEnd,
    BattleScript_IntimidateFail,
    BattleScript_IntimidateAbilityFail,
    BattleScript_IntimidateActivationAnimLoop,
    gFlashFireStringIds,
    gBRNPreventionStringIds,
    gPRLZPreventionStringIds,
    gPSNPreventionStringIds,
    gInobedientStringIds,
    BattleScript_DoSelfConfusionDmg,
    BattleScript_BerryCureParRet,
    BattleScript_BerryCurePsnRet,
    BattleScript_BerryCureBrnRet,
    BattleScript_BerryCureFrzRet,
    BattleScript_BerryCureSlpRet,
    BattleScript_BerryCureConfusionRet,
    BattleScript_BerryCureChosenStatusRet,
    gBerryEffectStringIds,
    BattleScript_WhiteHerbRet,
    BattleScript_ItemHealHP_Ret,
    BattleScript_BerryStatRaiseDoStatUp,
    BattleScript_StatUp,
    BattleScript_OldManThrowBall,
    BattleScript_PokedudeThrowBall,
    &gLastUsedItem,
    BattleScript_SafariNoIncGameStat,
    BattleScript_CaughtPokemonSkipNewDex,
    BattleScript_CaughtPokemonSkipNickname,
    gCaughtMonStringIds,
    BattleScript_CaughtPokemonDone,
    gBallEscapeStringIds,
    BattleScript_CatchFailEnd,
    &gNumSafariBalls,
    gTrainerItemCuredStatusStringIds,
    BattleScript_PokeFluteWakeUp,
    BattleScript_PokeFluteEnd,
    gSafariReactionStringIds,
    &gBasicHitSplatSpriteTemplate,
    AnimTask_ShakeMon,
    DoubleSlapLeft,
    DoubleSlapRight,
    DoubleSlapContinue,
    &gPoisonPowderParticleSpriteTemplate,
    &gStunSporeParticleSpriteTemplate,
    &gSleepPowderParticleSpriteTemplate,
    &gSwiftStarSpriteTemplate,
    AnimTask_ShakeMon2,
    AnimTask_ShakeAndSinkMon,
    &gSlideMonToOriginalPosSpriteTemplate,
    AnimTask_TranslateMonEllipticalRespectSide,
    &gHorizontalLungeSpriteTemplate,
    &gVerticalDipSpriteTemplate,
    &gSlideMonToOffsetSpriteTemplate,
    AnimTask_ShakeMonInPlace,
    SupersonicRing,
    &gSupersonicRingSpriteTemplate,
    ScreechRing,
    AnimTask_SwayMon,
    &gScreechRingSpriteTemplate,
    &gFireSpiralOutwardSpriteTemplate,
    AnimTask_BlendMonInAndOut,
    FireSpreadEffect,
    &gPinMissileSpriteTemplate,
    &gIcicleSpearSpriteTemplate,
    AnimTask_WindUpLunge,
    &gComplexPaletteBlendSpriteTemplate,
    &gSimplePaletteBlendSpriteTemplate,
    AnimTask_RotateMonSpriteToSide,
    &gLinearStingerSpriteTemplate,
    PoisonBubblesEffect,
    &gHandleInvertHitSplatSpriteTemplate,
    SoundTask_FireBlast,
    FireBlastRing,
    AnimTask_BlendBattleAnimPal,
    FireBlastCross,
    &gFireBlastRingSpriteTemplate,
    &gFireBlastCrossSpriteTemplate,
    &gLeechSeedSpriteTemplate,
    &gEmberSpriteTemplate,
    EmberFireHit,
    &gEmberFlareSpriteTemplate,
    &gMegaPunchKickSpriteTemplate,
    SetImpactBackground,
    AnimTask_IsContest,
    SetImpactContestsBG,
    AnimTask_IsTargetPlayerSide,
    SetImpactOpponentBG,
    SetImpactPlayerBG,
    SetImpactBackgroundRet,
    CometPunchLeft,
    CometPunchRight,
    &gFistFootSpriteTemplate,
    CometPunchContinue,
    SonicBoomProjectile,
    SonicBoomHit,
    &gSonicBoomSpriteTemplate,
    AnimTask_ElectricBolt,
    ElectricityEffect,
    &gThunderboltOrbSpriteTemplate,
    &gSparkElectricityFlashingSpriteTemplate,
    &gThunderWaveSpriteTemplate,
    BeatUpLeft,
    BeatUpRight,
    BeatUpContinue,
    &gStompFootSpriteTemplate,
    &gCuttingSliceSpriteTemplate,
    AnimTask_ScaleMonAndRestore,
    &gHiddenPowerOrbSpriteTemplate,
    &gHiddenPowerOrbScatterSpriteTemplate,
    AnimTask_BlendColorCycle,
    &gReversalOrbSpriteTemplate,
    AnimTask_ShakeTargetBasedOnMovePowerOrDmg,
    PursuitNormal,
    PursuitOnSwitchout,
    PursuitContinue,
    &gSwordsDanceBladeSpriteTemplate,
    AnimTask_FlashAnimTagWithColor,
    AnimTask_BlendColorCycleExclude,
    &gPsychUpSpiralSpriteTemplate,
    DizzyPunchLunge,
    &gDizzyPunchDuckSpriteTemplate,
    FireSpinEffect,
    &gFireSpinSpriteTemplate,
    AnimTask_IsFuryCutterHitRight,
    FuryCutterLeft,
    FuryCutterRight,
    AnimTask_GetFuryCutterHitCount,
    FuryCutterContinue2,
    FuryCutterMedium,
    FuryCutterStrong,
    FuryCutterStrongest,
    FuryCutterContinue,
    SelfDestructExplode,
    &gExplosionSpriteTemplate,
    &gSlamHitSpriteTemplate,
    &gVineWhipSpriteTemplate,
    &gBowMonSpriteTemplate,
    AnimTask_DrillPeckHitSplats,
    &gSmallBubblePairSpriteTemplate,
    RisingWaterHitEffect,
    &gWaterHitSplatSpriteTemplate,
    &gSmallDriftingBubblesSpriteTemplate,
    Explosion1,
    AnimTask_SetGrayscaleOrOriginalPal,
    AnimTask_DefenseCurlDeformMon,
    &gEclipsingOrbSpriteTemplate,
    &gProtectSpriteTemplate,
    &gSpinningSparkleSpriteTemplate,
    AnimTask_GetFrustrationPowerLevel,
    Frustration_Strongest,
    Frustration_Strong,
    Frustration_Medium,
    Frustration_Weak,
    &gAngerMarkSpriteTemplate,
    Frustration_Continue,
    AnimTask_StrongFrustrationGrowAndShrink,
    &gWeakFrustrationAngerMarkSpriteTemplate,
    &gGuardRingSpriteTemplate,
    &gPainSplitProjectileSpriteTemplate,
    AnimTask_PainSplitMovement,
    &gViceGripSpriteTemplate,
    &gGuillotineSpriteTemplate,
    &gCoinThrowSpriteTemplate,
    &gFallingCoinSpriteTemplate,
    &gOutrageFlameSpriteTemplate,
    OutrageFlames,
    &gSparkElectricitySpriteTemplate,
    &gRedHeartProjectileSpriteTemplate,
    &gRedHeartBurstSpriteTemplate,
    AnimTask_HeartsBackground,
    &gRedHeartRisingSpriteTemplate,
    GrowthEffect,
    &gWhirlwindLineSpriteTemplate,
    AnimTask_SlideOffScreen,
    SoundTask_AdjustPanningVar,
    AnimTask_BlendColorCycleByTag,
    &gConfuseRayBallBounceSpriteTemplate,
    &gConfuseRayBallSpiralSpriteTemplate,
    &gLockOnTargetSpriteTemplate,
    &gLockOnMoveTargetSpriteTemplate,
    &gMeanLookEyeSpriteTemplate,
    &gShakeMonOrTerrainSpriteTemplate,
    &gFallingRockSpriteTemplate,
    RockSlideRocks,
    BulbblebeamCreateBubbles,
    WaterBubblesEffectShort,
    &gWaterBubbleProjectileSpriteTemplate,
    IcyWindSwirlingSnowballs,
    IceSpikesEffectLong,
    &gSwirlingSnowballSpriteTemplate,
    &gBlackBallSpriteTemplate,
    AnimTask_SmokescreenImpact,
    &gBlackSmokeSpriteTemplate,
    &gConversionSpriteTemplate,
    AnimTask_ConversionAlphaBlend,
    &gConversion2SpriteTemplate,
    AnimTask_Conversion2AlphaBlend,
    &gSlidingKickSpriteTemplate,
    &gFlashingHitSplatSpriteTemplate,
    &gHornHitSpriteTemplate,
    FuryAttackRight,
    FuryAttackLeft,
    FuryAttackContinue,
    HornDrillInContest,
    AnimTask_StartSlidingBg,
    HornDrillContinue,
    AnimTask_ThrashMoveMonHorizontal,
    AnimTask_ThrashMoveMonVertical,
    &gFistFootRandomPosSpriteTemplate,
    AnimTask_MusicNotesRainbowBlend,
    &gWavyMusicNotesSpriteTemplate,
    AnimTask_MusicNotesClearRainbowBlend,
    AnimTask_HorizontalShake,
    FissureDirtPlumeFar,
    FissureDirtPlumeClose,
    AnimTask_PositionFissureBgOnBattler,
    &gDirtPlumeSpriteTemplate,
    DigSetUp,
    DigUnleash,
    &gDirtMoundSpriteTemplate,
    AnimTask_DigDownMovement,
    DigThrowDirt,
    DigEnd,
    AnimTask_DigUpMovement,
    SetPsychicBackground,
    AnimTask_MeditateStretchAttacker,
    UnsetPsychicBackground,
    AnimTask_TraceMonBlended,
    AnimTask_Teleport,
    AnimTask_DoubleTeam,
    AnimTask_Minimize,
    &gThoughtBubbleSpriteTemplate,
    &gMetronomeFingerSpriteTemplate,
    SkullBashSetUp,
    SkullBashAttack,
    SkullBashSetUpHeadDown,
    SkullBashEnd,
    &gSlideMonToOffsetAndBackSpriteTemplate,
    AnimTask_SkullBashPosition,
    &gQuestionMarkSpriteTemplate,
    &gBentSpoonSpriteTemplate,
    &gKinesisZapEnergySpriteTemplate,
    AnimTask_GlareEyeDots,
    &gEyeSparkleSpriteTemplate,
    AnimTask_ScaryFace,
    AnimTask_ShakeTargetInPattern,
    AnimTask_BarrageBall,
    SkyAttackSetUp,
    SkyAttackUnleash,
    AnimTask_GetTargetIsAttackerPartner,
    SkyAttackSetUpAgainstOpponent,
    SkyAttackSetUpAgainstPartner,
    SkyAttackEnd,
    AnimTask_BlendBattleAnimPalExclude,
    SetSkyBg,
    AnimTask_AttackerFadeToInvisible,
    SoundTask_PlaySE2WithPanning,
    &gSkyAttackBirdSpriteTemplate,
    SoundTask_PlaySE1WithPanning,
    AnimTask_AttackerFadeFromInvisible,
    UnsetSkyBg,
    AnimTask_Flash,
    AnimTask_Splash,
    AnimTask_AcidArmor,
    &gSharpenSphereSpriteTemplate,
    &gSuperFangSpriteTemplate,
    &gSlashSliceSpriteTemplate,
    &gMovementWavesSpriteTemplate,
    AnimTask_SketchDrawMon,
    &gPencilSpriteTemplate,
    NightmareInContest,
    AnimTask_NightmareClone,
    AnimTask_FlailMovement,
    &gRandomPosHitSplatSpriteTemplate,
    AnimTask_SpiteTargetShadow,
    AnimTask_GetAttackerSide,
    MachPunchAgainstPlayer,
    AnimTask_AttackerPunchWithTrace,
    MachPunchContinue,
    &gForesightMagnifyingGlassSpriteTemplate,
    AnimTask_DestinyBondWhiteShadow,
    EndureEffect,
    &gEndureEnergySpriteTemplate,
    AnimTask_RockMonBackAndForth,
    &gMagentaHeartSpriteTemplate,
    AnimTask_Rollout,
    &gFalseSwipeSliceSpriteTemplate,
    &gFalseSwipePositionedSliceSpriteTemplate,
    AnimTask_GrowAndShrink,
    &gBreathPuffSpriteTemplate,
    &gMilkBottleSpriteTemplate,
    &gThinRingExpandingSpriteTemplate,
    HealingEffect2,
    AnimTask_IsPowerOver99,
    MagnitudeRegular,
    MagnitudeIntense,
    MagnitudeEnd,
    &gRapidSpinSpriteTemplate,
    AnimTask_RapinSpinMonElevation,
    &gMoonSpriteTemplate,
    AnimTask_AlphaFadeIn,
    &gMoonlightSparkleSpriteTemplate,
    AnimTask_MoonlightEndFade,
    HealingEffect,
    ExtremeSpeedAgainstPlayer,
    AnimTask_AttackerStretchAndDisappear,
    AnimTask_SetAttackerInvisibleWaitForSignal,
    AnimTask_ExtremeSpeedImpact,
    &gMonEdgeHitSplatSpriteTemplate,
    AnimTask_SpeedDust,
    AnimTask_ExtremeSpeedMonReappear,
    ExtremeSpeedContinue,
    AnimTask_UproarDistortion,
    &gUproarRingSpriteTemplate,
    &gJaggedMusicNoteSpriteTemplate,
    AnimTask_BlendParticle,
    AnimTask_LoadSandstormBackground,
    AnimTask_BlendBackground,
    AnimTask_MoveHeatWaveTargets,
    &gFlyingSandCrescentSpriteTemplate,
    AnimTask_Hail,
    AnimTask_TormentAttacker,
    AnimTask_InitMementoShadow,
    AnimTask_MoveAttackerMementoShadow,
    AnimTask_MementoHandleBg,
    AnimTask_MoveTargetMementoShadow,
    AnimTask_SquishAndSweatDroplets,
    AnimTask_FacadeColorBlend,
    &gSmellingSaltsHandSpriteTemplate,
    AnimTask_SmellingSaltsSquish,
    &gSmellingSaltExclamationSpriteTemplate,
    &gFollowMeFingerSpriteTemplate,
    AnimTask_ElectricChargingParticles,
    &gGrowingChargeOrbSpriteTemplate,
    &gElectricPuffSpriteTemplate,
    &gTauntFingerSpriteTemplate,
    AnimTask_HelpingHandAttackerMovement,
    &gHelpingHandClapSpriteTemplate,
    &gAssistPawprintSpriteTemplate,
    &gSuperpowerOrbSpriteTemplate,
    &gSuperpowerRockSpriteTemplate,
    &gSuperpowerFireballSpriteTemplate,
    &gRecycleSpriteTemplate,
    BrickBreakNormal,
    BrickBreakShatteredWall,
    &gBrickBreakWallSpriteTemplate,
    &gBrickBreakWallShardSpriteTemplate,
    AnimTask_DeepInhale,
    &gYawnCloudSpriteTemplate,
    AnimTask_EruptionLaunchRocks,
    &gEruptionFallingRockSpriteTemplate,
    AnimTask_SkillSwap,
    AnimTask_ImprisonOrbs,
    &gRedXSpriteTemplate,
    AnimTask_GrudgeFlames,
    AnimTask_SetCamouflageBlend,
    &gTailGlowOrbSpriteTemplate,
    AnimTask_FadeScreenToWhite,
    &gLusterPurgeCircleSpriteTemplate,
    &gMistBallSpriteTemplate,
    AnimTask_MistBallFog,
    &gFallingFeatherSpriteTemplate,
    AnimTask_TeeterDanceMovement,
    &gFastFlyingMusicNotesSpriteTemplate,
    &gMudsportMudSpriteTemplate,
    &gNeedleArmSpikeSpriteTemplate,
    AnimTask_SlackOffSquish,
    &gClawSlashSpriteTemplate,
    &gAromatherapySmallFlowerSpriteTemplate,
    &gAromatherapyBigFlowerSpriteTemplate,
    AnimTask_StatusClearedEffect,
    &gSparklingStarsSpriteTemplate,
    &gBlendThinRingExpandingSpriteTemplate,
    &gTearDropSpriteTemplate,
    AnimTask_AirCutterProjectile,
    &gAirCutterSliceSpriteTemplate,
    AnimTask_OdorSleuthMovement,
    AnimTask_WaterSpoutLaunch,
    AnimTask_WaterSpoutRain,
    AnimTask_ExtrasensoryDistortion,
    AnimTask_TransparentCloneGrowAndShrink,
    AnimTask_MetallicShine,
    &gBlockXSpriteTemplate,
    RoarEffect,
    SoundTask_PlayCryHighPitch,
    &gVoltTackleOrbSlideSpriteTemplate,
    AnimTask_VoltTackleBolt,
    AnimTask_VoltTackleAttackerReappear,
    AnimTask_WaterSport,
    AnimTask_SetAllNonAttackersInvisiblity,
    &gThinRingShrinkingSpriteTemplate,
    AnimTask_LeafBlade,
    &gCrossImpactSpriteTemplate,
    AnimTask_DragonDanceWaver,
    AnimTask_BlendPalInAndOutByTag,
    &gDragonDanceOrbSpriteTemplate,
    &gGrowingShockWaveOrbSpriteTemplate,
    AnimTask_ShockWaveProgressingBolt,
    AnimTask_ShockWaveLightning,
    BellyDrumRight,
    &gSlowFlyingMusicNotesSpriteTemplate,
    BellyDrumLeft,
    &gBellyDrumHandSpriteTemplate,
    &gOpeningEyeSpriteTemplate,
    &gWhiteHaloSpriteTemplate,
    MindReaderEyeSpikeEffect,
    &gTealAlertSpriteTemplate,
    &gIceCrystalSpiralInwardSmall,
    &gIceCrystalSpiralInwardLarge,
    IceCrystalEffectShort,
    &gSleepLetterZSpriteTemplate,
    FutureSight,
    FutureSightContinue,
    AnimTask_InvertScreenColor,
    &gLightningSpriteTemplate,
    &gFirePlumeSpriteTemplate,
    &gLargeFlameSpriteTemplate,
    &gLargeFlameScatterSpriteTemplate,
    &gScratchSpriteTemplate,
    &gDragonBreathFireSpriteTemplate,
    SoundTask_PlayDoubleCry,
    SoundTask_WaitForCry,
    &gRoarNoiseLineSpriteTemplate,
    SnoreEffect,
    &gSnoreZSpriteTemplate,
    &gLightScreenWallSpriteTemplate,
    SpecialScreenSparkle,
    &gSpecialScreenSparkleSpriteTemplate,
    &gMirrorCoatWallSpriteTemplate,
    &gReflectWallSpriteTemplate,
    &gReflectSparkleSpriteTemplate,
    &gBarrierWallSpriteTemplate,
    WaterBubblesEffectLong,
    SmogCloud,
    &gSmogCloudSpriteTemplate,
    AnimTask_InitAttackerFadeFromInvisible,
    SandAttackDirt,
    &gSandAttackDirtSpriteTemplate,
    MudSlapMud,
    &gMudSlapMudSpriteTemplate,
    &gDragonRageFireSpitSpriteTemplate,
    &gDragonRageFirePlumeSpriteTemplate,
    AnimTask_CreateRaindrops,
    &gSharpTeethSpriteTemplate,
    &gClampJawSpriteTemplate,
    SoundTask_LoopSEAdjustPanning,
    &gIceBeamOuterCrystalSpriteTemplate,
    IceBeamCreateCrystals,
    &gIceBeamInnerCrystalSpriteTemplate,
    AnimTask_Withdraw,
    AnimTask_RotateAuroraRingColors,
    AuroraBeamCreateRings,
    &gAuroraBeamRingSpriteTemplate,
    SolarBeamSetUp,
    SolarBeamUnleash,
    SolarBeamAbsorbEffect,
    SolarBeamEnd,
    &gPowerAbsorptionOrbSpriteTemplate,
    SetSolarBeamBg,
    AnimTask_CreateSmallSolarBeamOrbs,
    &gSolarBeamBigOrbSpriteTemplate,
    SolarBeamUnleash1,
    UnsetSolarBeamBg,
    BlizzardAgainstPlayer,
    BlizzardIceCrystals,
    IceCrystalEffectLong,
    &gBlizzardIceCrystalSpriteTemplate,
    BlizzardContinue,
    PowderSnowSnowballs,
    &gPowderSnowSnowballSpriteTemplate,
    AnimTask_StartSinAnimTimer,
    HydroPumpBeams,
    HydroPumpHitSplats,
    &gHydroPumpOrbSpriteTemplate,
    SignalBeamOrbs,
    &gSignalBeamRedOrbSpriteTemplate,
    &gSignalBeamGreenOrbSpriteTemplate,
    AbsorbEffect,
    &gAbsorptionOrbSpriteTemplate,
    MegaDrainAbsorbEffect,
    GigaDrainAbsorbEffect,
    &gLeechLifeNeedleSpriteTemplate,
    GrantingStarsEffect,
    ToxicBubbles,
    &gToxicBubbleSpriteTemplate,
    &gSludgeProjectileSpriteTemplate,
    SludgeBombProjectile,
    &gSludgeBombHitParticleSpriteTemplate,
    &gAcidPoisonBubbleSpriteTemplate,
    &gAcidPoisonDropletSpriteTemplate,
    &gBonemerangSpriteTemplate,
    &gSpinningBoneSpriteTemplate,
    &gSpikesSpriteTemplate,
    MegahornInContest,
    &gMegahornHornSpriteTemplate,
    MegahornContinue,
    &gEllipticalGustSpriteTemplate,
    AnimTask_AnimateGustTornadoPalette,
    AnimTask_TranslateMonElliptical,
    &gGustToTargetSpriteTemplate,
    AnimTask_RotateMonToSideAndRestore,
    AeroblastBeam,
    &gAirWaveCrescentSpriteTemplate,
    &gWaterGunProjectileSpriteTemplate,
    &gWaterGunDropletSpriteTemplate,
    AnimTask_CreateSurfWave,
    FlamethrowerCreateFlames,
    &gFlamethrowerFlameSpriteTemplate,
    WhirlpoolEffect,
    &gWhirlpoolSpriteTemplate,
    FlySetUp,
    FlyUnleash,
    &gFlyBallUpSpriteTemplate,
    FlyEnd,
    &gFlyBallAttackSpriteTemplate,
    BounceSetUp,
    BounceUnleash,
    &gBounceBallShrinkSpriteTemplate,
    BounceEnd,
    &gBounceBallLandSpriteTemplate,
    &gKarateChopSpriteTemplate,
    &gCrossChopHandSpriteTemplate,
    &gJumpKickSpriteTemplate,
    TripleKickLeft,
    TripleKickRight,
    TripleKickCenter,
    TripleKickContinue,
    &gRockFragmentSpriteTemplate,
    SubmissionHit,
    SunnyDayLightRay,
    &gSunlightRaySpriteTemplate,
    CreateCottonSpores,
    &gSporeParticleSpriteTemplate,
    AnimTask_SporeDoubleBattle,
    CreateSpore,
    &gPetalDanceBigFlowerSpriteTemplate,
    &gPetalDanceSmallFlowerSpriteTemplate,
    &gRazorLeafParticleSpriteTemplate,
    &gRazorLeafCutterSpriteTemplate,
    &gAncientPowerRockSpriteTemplate,
    &gOctazookaBallSpriteTemplate,
    &gOctazookaSmokeSpriteTemplate,
    MistCloud,
    &gMistCloudSpriteTemplate,
    AnimTask_HazeScrollingFog,
    &gFireSpiralInwardSpriteTemplate,
    &gFireSpreadSpriteTemplate,
    &gLeerSpriteTemplate,
    DreamEaterAbsorb,
    &gPoisonGasCloudSpriteTemplate,
    BindWrap,
    BindWrapSqueezeTarget,
    PsybeamRings,
    &gGoldRingSpriteTemplate,
    HypnosisRings,
    PsywaveRings,
    &gPsywaveRingSpriteTemplate,
    &gZapCannonBallSpriteTemplate,
    &gZapCannonSparkSpriteTemplate,
    AnimTask_NightShadeClone,
    &gEggThrowSpriteTemplate,
    &gShadowBallSpriteTemplate,
    &gLickSpriteTemplate,
    BideSetUp,
    BideUnleash,
    StringShotThread,
    &gStringWrapSpriteTemplate,
    &gWebThreadSpriteTemplate,
    SpiderWebThread,
    &gSpiderWebSpriteTemplate,
    RazorWindSetUp,
    RazorWindUnleash,
    &gRazorWindTornadoSpriteTemplate,
    RazorWindEnd,
    AnimTask_GrowAndGrayscale,
    RecoverAbsorbEffect,
    AnimTask_ShrinkTargetCopy,
    &gMimicOrbSpriteTemplate,
    &gConstrictBindingSpriteTemplate,
    CurseGhost,
    CurseStats,
    AnimTask_CurseStretchingBlackBg,
    &gCurseNailSpriteTemplate,
    CurseGhostShakeFromNail,
    &gCurseGhostSpriteTemplate,
    CurseStats1,
    AnimTask_DrawFallingWhiteLinesOnAttacker,
    &gSoftBoiledEggSpriteTemplate,
    AnimTask_LoadMusicNotesPals,
    &gBellSpriteTemplate,
    &gHealBellMusicNoteSpriteTemplate,
    HealBellRing,
    AnimTask_FreeMusicNotesPals,
    AnimTask_FakeOut,
    AnimTask_StretchTargetUp,
    &gAngelSpriteTemplate,
    &gDevilSpriteTemplate,
    &gPinkHeartSpriteTemplate,
    &gFurySwipesSpriteTemplate,
    &gIngrainRootSpriteTemplate,
    &gIngrainOrbSpriteTemplate,
    AnimTask_IsHealingMove,
    &gPresentSpriteTemplate,
    PresentDamage,
    PresentHeal,
    &gPresentHealParticleSpriteTemplate,
    &gBatonPassPokeballSpriteTemplate,
    &gPerishSongMusicNoteSpriteTemplate,
    &gPerishSongMusicNote2SpriteTemplate,
    &gLetterZSpriteTemplate,
    HyperFangInContest,
    HyperFangOnOpponent,
    HyperFangOnPlayer,
    &gFangSpriteTemplate,
    HyperFangContinue,
    &gTriAttackTriangleSpriteTemplate,
    &gWillOWispOrbSpriteTemplate,
    &gWillOWispFireSpriteTemplate,
    AnimTask_CreateSpotlight,
    AnimTask_HardwarePaletteFade,
    &gSpotlightSpriteTemplate,
    &gClappingHandSpriteTemplate,
    &gClappingHand2SpriteTemplate,
    AnimTask_RemoveSpotlight,
    &gTrickBagSpriteTemplate,
    AnimTask_StretchAttackerUp,
    &gWishStarSpriteTemplate,
    AnimTask_StockpileDeformMon,
    StockpileAbsorb,
    &gStockpileAbsorptionOrbSpriteTemplate,
    AnimTask_SpitUpDeformMon,
    &gSpitUpOrbSpriteTemplate,
    SpitUpStrong,
    SpitUpStrongest,
    SpitUpContinue,
    AnimTask_SwallowDeformMon,
    SwallowEffect,
    SwallowGood,
    SwallowBest,
    &gSwallowBlueOrbSpriteTemplate,
    SwallowContinue,
    AnimTask_TransformMon,
    AnimTask_MorningSunLightBeam,
    MorningSunStar,
    &gGreenStarSpriteTemplate,
    &gSweetScentPetalSpriteTemplate,
    SweetScentEffect,
    HyperBeamOrbs,
    &gHyperBeamOrbSpriteTemplate,
    &gFlatterSpotlightSpriteTemplate,
    CreateFlatterConfetti,
    &gFlatterConfettiSpriteTemplate,
    AnimTask_RolePlaySilhouette,
    &gSpinningHandOrFootSpriteTemplate,
    HyperVoiceEffect,
    SoundTask_PlayCryWithEcho,
    &gHyperVoiceRingSpriteTemplate,
    AnimTask_ShakeBattleTerrain,
    SandTombSwirlingDirt,
    &gSwirlingDirtSpriteTemplate,
    AnimTask_FrozenIceCube,
    &gArmThrustHandSpriteTemplate,
    ArmThrustRight,
    ArmThrustLeft,
    ArmThrustContinue,
    &gBulletSeedSpriteTemplate,
    DragonClawFireSpiral,
    MudShotOrbs,
    &gMudShotOrbSpriteTemplate,
    &gMeteorMashStarSpriteTemplate,
    &gRevengeSmallScratchSpriteTemplate,
    &gRevengeBigScratchSpriteTemplate,
    &gPersistHitSplatSpriteTemplate,
    AnimTask_MonToSubstitute,
    &gFrenzyPlantRootSpriteTemplate,
    MetalSoundRings,
    &gMetalSoundSpriteTemplate,
    FocusPunch,
    FocusPunchInContest,
    FocusPunchOnOpponent,
    FocusPunchOnPlayer,
    &gFocusPunchFistSpriteTemplate,
    FocusPunchEnd,
    FocusPunchContinue,
    AnimTask_GetReturnPowerLevel,
    ReturnWeak,
    ReturnMedium,
    ReturnStrong,
    ReturnStrongest,
    ReturnContinue,
    ReturnStrongestHit,
    AnimTask_BlendNonAttackerPalettes,
    &gGrantingStarsSpriteTemplate,
    &gRockTombRockSpriteTemplate,
    AnimTask_GetTargetSide,
    SilverWindOnPlayer,
    &gSilverWindBigSparkSpriteTemplate,
    &gSilverWindMediumSparkSpriteTemplate,
    &gSilverWindSmallSparkSpriteTemplate,
    SilverWindContinue,
    DiveSetUp,
    DiveAttack,
    &gDiveBallSpriteTemplate,
    &gDiveWaterSplashSpriteTemplate,
    DiveSetUpWaterDroplets,
    &gSprayWaterDropletSpriteTemplate,
    DiveAttackWaterDroplets,
    &gRockBlastRockSpriteTemplate,
    AnimTask_AllocBackupPalBuffer,
    AnimTask_CopyPalUnfadedToBackup,
    AnimTask_CopyPalFadedToUnfaded,
    &gOverheatFlameSpriteTemplate,
    AnimTask_CopyPalUnfadedFromBackup,
    AnimTask_FreeBackupPalBuffer,
    &gHydroCannonChargeSpriteTemplate,
    HydroCannonBeam,
    &gHydroCannonBeamSpriteTemplate,
    AnimTask_GetSeismicTossDamageLevel,
    AnimTask_MoveSeismicTossBg,
    AnimTask_SeismicTossBgAccelerateDownAtEnd,
    SeismicTossWeak,
    SeismicTossMedium,
    SeismicTossStrong,
    SeismicTossRockScatter1,
    SeismicTossRockScatter2,
    SeismicTossContinue,
    &gRockScatterSpriteTemplate,
    &gMagicCoatWallSpriteTemplate,
    &gWaterPulseBubbleSpriteTemplate,
    &gWaterPulseRingSpriteTemplate,
    &gPsychoBoostOrbSpriteTemplate,
    &gKnockOffStrikeSpriteTemplate,
    GetIsDoomDesireHitTurn,
    AnimTask_DoomDesireLightBeam,
    AnimTask_MoveSkyUppercutBg,
    AnimTask_GetBattleTerrain,
    Move_NEEDLE_ARM,
    Move_MAGICAL_LEAF,
    Move_MUD_SHOT,
    Move_WATERFALL,
    Move_SURF,
    Move_BUBBLE_BEAM,
    Move_ROCK_THROW,
    Move_BITE,
    Move_STRENGTH,
    Move_SLAM,
    &gTwisterLeafSpriteTemplate,
    &gTwisterRockSpriteTemplate,
    AnimTask_CycleMagicalLeafPal,
    AnimTask_GetRolloutCounter,
    IceBallSetIceBg,
    &gIceBallChunkSpriteTemplate,
    IceBallWeakest,
    IceBallWeak,
    IceBallMediun,
    IceBallStrong,
    IceBallStrongest,
    IceBallUnsetIceBg,
    IceBallContinue,
    IceBallEnd,
    IceBallImpactShard,
    IceBallContinue2,
    &gIceBallImpactShardSpriteTemplate,
    &gWeatherBallUpSpriteTemplate,
    AnimTask_GetWeather,
    WeatherBallNormal,
    WeatherBallFire,
    WeatherBallWater,
    WeatherBallSandstorm,
    WeatherBallIce,
    &gWeatherBallNormalDownSpriteTemplate,
    &gWeatherBallFireDownSpriteTemplate,
    &gWeatherBallWaterDownSpriteTemplate,
    &gWeatherBallRockDownSpriteTemplate,
    &gWeatherBallIceDownSpriteTemplate,
    &gIceCrystalHitLargeSpriteTemplate,
    &gIceCrystalHitSmallSpriteTemplate,
    &gIceGroundSpikeSpriteTemplate,
    &gHealingBlueStarSpriteTemplate,
    &gPoisonBubbleSpriteTemplate,
    &gWaterBubbleSpriteTemplate,
    &gElectricitySpriteTemplate,
    &gConfusionDuckSpriteTemplate,
    AnimTask_SetPsychicBackground,
    SetSkyBgContest,
    SetSkyBgContinue,
    SetSolarBeamBgContest,
    SetSolarBeamBgOpponent,
    SetSolarBeamBgPlayer,
    SetSolarBeamBgContinue,
    ConfusionEffect,
    BurnFlame,
    &gBurnFlameSpriteTemplate,
    &gNightmareDevilSpriteTemplate,
    AnimTask_IsMonInvisible,
    CastformChangeSkipAnim,
    CastformChangeContinue,
    AnimTask_CastformGfxChange,
    AnimTask_StatsChange,
    AnimTask_SubstituteFadeToInvisible,
    AnimTask_SwapMonSpriteToFromSubstitute,
    AnimTask_SafariOrGhost_DecideAnimSides,
    AnimTask_LoadBaitGfx,
    &gSafariBaitSpriteTemplate,
    AnimTask_FreeBaitGfx,
    &gKnockOffItemSpriteTemplate,
    AnimTask_GetTrappedMoveAnimId,
    Status_FireSpin,
    Status_Whirlpool,
    Status_Clamp,
    Status_SandTomb,
    Status_BindWrap,
    &gSmokeBallEscapeCloudSpriteTemplate,
    AnimTask_SlideMonForFocusBand,
    Move_SUNNY_DAY,
    Move_SANDSTORM,
    Move_HAIL,
    AnimTask_GetBattlersFromArg,
    Move_ABSORB,
    AnimTask_SetAnimAttackerAndTargetForEffectAtk,
    AnimTask_SetTargetToEffectBattler,
    &gItemStealSpriteTemplate,
    AnimTask_SetAnimAttackerAndTargetForEffectTgt,
    SnatchMoveTrySwapFromSubstitute,
    AnimTask_IsTargetSameSide,
    SnatchOpposingMonMove,
    SnatchPartnerMonMove,
    SnatchMoveTrySwapToSubstitute,
    AnimTask_SnatchOpposingMonMove,
    SnatchMoveContinue,
    AnimTask_SnatchPartnerMove,
    AnimTask_SetAnimTargetToBattlerTarget,
    AnimTask_GhostGetOut,
    &gSafariRockTemplate,
    AnimTask_SafariGetReaction,
    SafariReaction_WatchingCarefully,
    SafariReaction_Angry,
    SafariReaction_Eating,
    AnimTask_IsAttackerBehindSubstitute,
    SnatchMoveSwapSubstituteForMon,
    SnatchMoveTrySwapFromSubstituteEnd,
    SnatchMoveSwapMonForSubstitute,
    SnatchMoveTrySwapToSubstituteEnd,
    AnimTask_LoadHealthboxPalsForLevelUp,
    AnimTask_FlashHealthboxOnLevelUp,
    AnimTask_FreeHealthboxPalsForLevelUp,
    AnimTask_SwitchOutBallEffect,
    AnimTask_SwitchOutShrinkMon,
    AnimTask_LoadBallGfx,
    AnimTask_ThrowBall,
    AnimTask_IsBallBlockedByTrainerOrDodged,
    BallThrowTrainerBlock,
    BallThrowGhostDodged,
    AnimTask_FreeBallGfx,
    BallThrowEnd,
    AnimTask_ThrowBallSpecial,
    AI_CheckBadMove_CheckSoundproof,
    Score_Minus10,
    CheckIfVoltAbsorbCancelsElectric,
    CheckIfWaterAbsorbCancelsWater,
    CheckIfFlashFireCancelsFire,
    CheckIfWonderGuardCancelsMove,
    CheckIfLevitateCancelsGroundMove,
    Score_Minus12,
    AI_CheckBadMove_CheckEffect,
    AI_CBM_Sleep,
    AI_CBM_Explosion,
    AI_CBM_DreamEater,
    AI_CBM_AttackUp,
    AI_CBM_DefenseUp,
    AI_CBM_SpeedUp,
    AI_CBM_SpAtkUp,
    AI_CBM_SpDefUp,
    AI_CBM_AccUp,
    AI_CBM_EvasionUp,
    AI_CBM_AttackDown,
    AI_CBM_DefenseDown,
    AI_CBM_SpeedDown,
    AI_CBM_SpAtkDown,
    AI_CBM_SpDefDown,
    AI_CBM_AccDown,
    AI_CBM_EvasionDown,
    AI_CBM_Haze,
    AI_CBM_HighRiskForDamage,
    AI_CBM_Roar,
    AI_CBM_Poison,
    AI_CBM_LightScreen,
    AI_CBM_OneHitKO,
    AI_CBM_Mist,
    AI_CBM_FocusEnergy,
    AI_CBM_Confuse,
    AI_CBM_Reflect,
    AI_CBM_Paralyze,
    AI_CBM_Substitute,
    AI_CBM_LeechSeed,
    AI_CBM_Disable,
    AI_CBM_Encore,
    AI_CBM_DamageDuringSleep,
    AI_CBM_CantEscape,
    AI_CBM_Nightmare,
    AI_CBM_Curse,
    AI_CBM_Spikes,
    AI_CBM_Foresight,
    AI_CBM_PerishSong,
    AI_CBM_Sandstorm,
    AI_CBM_Attract,
    AI_CBM_Safeguard,
    AI_CBM_Magnitude,
    AI_CBM_BatonPass,
    AI_CBM_RainDance,
    AI_CBM_SunnyDay,
    AI_CBM_BellyDrum,
    AI_CBM_FutureSight,
    AI_CBM_FakeOut,
    AI_CBM_Stockpile,
    AI_CBM_SpitUpAndSwallow,
    AI_CBM_Hail,
    AI_CBM_Torment,
    AI_CBM_WillOWisp,
    AI_CBM_Memento,
    AI_CBM_HelpingHand,
    AI_CBM_TrickAndKnockOff,
    AI_CBM_Ingrain,
    AI_CBM_Recycle,
    AI_CBM_Imprison,
    AI_CBM_Refresh,
    AI_CBM_MudSport,
    AI_CBM_Tickle,
    AI_CBM_CosmicPower,
    AI_CBM_BulkUp,
    AI_CBM_WaterSport,
    AI_CBM_CalmMind,
    AI_CBM_DragonDance,
    AI_CBM_Explosion_End,
    Score_Minus1,
    Score_Minus8,
    CheckIfAbilityBlocksStatChange,
    AI_CBM_Haze_End,
    AI_CBM_HighRiskForDamage_End,
    Score_Minus5,
    AI_CBM_Attract_CheckIfTargetIsFemale,
    AI_CBM_Attract_CheckIfTargetIsMale,
    AI_CBM_Attract_End,
    AI_CV_Sleep,
    AI_CV_Absorb,
    AI_CV_SelfKO,
    AI_CV_DreamEater,
    AI_CV_MirrorMove,
    AI_CV_AttackUp,
    AI_CV_DefenseUp,
    AI_CV_SpeedUp,
    AI_CV_SpAtkUp,
    AI_CV_SpDefUp,
    AI_CV_AccuracyUp,
    AI_CV_EvasionUp,
    AI_CV_AlwaysHit,
    AI_CV_AttackDown,
    AI_CV_DefenseDown,
    AI_CV_SpeedDown,
    AI_CV_SpAtkDown,
    AI_CV_SpDefDown,
    AI_CV_AccuracyDown,
    AI_CV_EvasionDown,
    AI_CV_Haze,
    AI_CV_Bide,
    AI_CV_Roar,
    AI_CV_Conversion,
    AI_CV_Heal,
    AI_CV_Toxic,
    AI_CV_LightScreen,
    AI_CV_Rest,
    AI_CV_OneHitKO,
    AI_CV_ChargeUpMove,
    AI_CV_SuperFang,
    AI_CV_Trap,
    AI_CV_HighCrit,
    AI_CV_Confuse,
    AI_CV_Reflect,
    AI_CV_Poison,
    AI_CV_Paralyze,
    AI_CV_SpeedDownFromChance,
    AI_CV_VitalThrow,
    AI_CV_Substitute,
    AI_CV_Recharge,
    AI_CV_Disable,
    AI_CV_Counter,
    AI_CV_Encore,
    AI_CV_PainSplit,
    AI_CV_Snore,
    AI_CV_LockOn,
    AI_CV_SleepTalk,
    AI_CV_DestinyBond,
    AI_CV_Flail,
    AI_CV_HealBell,
    AI_CV_Thief,
    AI_CV_Curse,
    AI_CV_Protect,
    AI_CV_Foresight,
    AI_CV_Endure,
    AI_CV_BatonPass,
    AI_CV_Pursuit,
    AI_CV_HealWeather,
    AI_CV_RainDance,
    AI_CV_SunnyDay,
    AI_CV_BellyDrum,
    AI_CV_PsychUp,
    AI_CV_MirrorCoat,
    AI_CV_SemiInvulnerable,
    AI_CV_FakeOut,
    AI_CV_SpitUp,
    AI_CV_Hail,
    AI_CV_Flatter,
    AI_CV_Facade,
    AI_CV_FocusPunch,
    AI_CV_SmellingSalt,
    AI_CV_Trick,
    AI_CV_ChangeSelfAbility,
    AI_CV_Superpower,
    AI_CV_MagicCoat,
    AI_CV_Recycle,
    AI_CV_Revenge,
    AI_CV_BrickBreak,
    AI_CV_KnockOff,
    AI_CV_Endeavor,
    AI_CV_Eruption,
    AI_CV_Imprison,
    AI_CV_Refresh,
    AI_CV_Snatch,
    AI_CV_MudSport,
    AI_CV_Overheat,
    AI_CV_WaterSport,
    AI_CV_DragonDance,
    AI_CV_SleepEncourageSlpDamage,
    AI_CV_Sleep_End,
    AI_CV_AbsorbEncourageMaybe,
    AI_CV_Absorb_End,
    AI_CV_SelfKO_Encourage1,
    AI_CV_SelfKO_Encourage2,
    AI_CV_SelfKO_End,
    Score_Minus3,
    AI_CV_SelfKO_Encourage4,
    AI_CV_SelfKO_Encourage3,
    AI_CV_DreamEater_ScoreDown1,
    AI_CV_DreamEater_End,
    AI_CV_MirrorMove2,
    AI_CV_MirrorMove_EncouragedMovesToMirror,
    AI_CV_MirrorMove_End,
    AI_CV_AttackUp2,
    AI_CV_AttackUp3,
    AI_CV_AttackUp_End,
    AI_CV_AttackUp_ScoreDown2,
    AI_CV_DefenseUp2,
    AI_CV_DefenseUp3,
    AI_CV_DefenseUp4,
    AI_CV_DefenseUp_End,
    AI_CV_DefenseUp_ScoreDown2,
    AI_CV_DefenseUp5,
    AI_CV_DefenseUp_PhysicalTypes,
    AI_CV_SpeedUp2,
    AI_CV_SpeedUp_End,
    AI_CV_SpAtkUp2,
    AI_CV_SpAtkUp3,
    AI_CV_SpAtkUp_End,
    AI_CV_SpAtkUp_ScoreDown2,
    AI_CV_SpDefUp2,
    AI_CV_SpDefUp3,
    AI_CV_SpDefUp4,
    AI_CV_SpDefUp_End,
    AI_CV_SpDefUp_ScoreDown2,
    AI_CV_SpDefUp5,
    AI_CV_SpDefUp_PhysicalTypes,
    AI_CV_AccuracyUp2,
    AI_CV_AccuracyUp_End,
    AI_CV_EvasionUp2,
    AI_CV_EvasionUp3,
    AI_CV_EvasionUp5,
    AI_CV_EvasionUp4,
    AI_CV_EvasionUp6,
    AI_CV_EvasionUp7,
    AI_CV_EvasionUp8,
    AI_CV_EvasionUp_End,
    AI_CV_EvasionUp_ScoreDown2,
    AI_CV_AlwaysHit_ScoreUp1,
    AI_CV_AlwaysHit2,
    AI_CV_AlwaysHit_End,
    AI_CV_AttackDown3,
    AI_CV_AttackDown2,
    AI_CV_AttackDown4,
    AI_CV_AttackDown_PhysicalTypeList,
    AI_CV_AttackDown_End,
    AI_CV_DefenseDown2,
    AI_CV_DefenseDown3,
    AI_CV_DefenseDown_End,
    AI_CV_SpeedDown2,
    AI_CV_SpeedDown_End,
    AI_CV_SpAtkDown3,
    AI_CV_SpAtkDown2,
    AI_CV_SpAtkDown4,
    AI_CV_SpAtkDown_SpecialTypeList,
    AI_CV_SpAtkDown_End,
    AI_CV_SpDefDown2,
    AI_CV_SpDefDown3,
    AI_CV_SpDefDown_End,
    AI_CV_AccuracyDown2,
    AI_CV_AccuracyDown3,
    AI_CV_AccuracyDown4,
    AI_CV_AccuracyDown5,
    AI_CV_AccuracyDown6,
    AI_CV_AccuracyDown7,
    AI_CV_AccuracyDown8,
    AI_CV_AccuracyDown_End,
    AI_CV_AccuracyDown_ScoreDown2,
    AI_CV_EvasionDown2,
    AI_CV_EvasionDown3,
    AI_CV_EvasionDown_End,
    AI_CV_Haze2,
    AI_CV_Haze3,
    AI_CV_Haze4,
    AI_CV_Haze_End,
    AI_CV_Bide_End,
    AI_CV_Roar2,
    AI_CV_Roar_End,
    AI_CV_Conversion2,
    AI_CV_Conversion_End,
    Score_Minus2,
    AI_CV_HealWeather_ScoreDown2,
    AI_CV_Heal3,
    AI_CV_Heal4,
    AI_CV_Heal_End,
    AI_CV_Heal5,
    AI_CV_Heal6,
    AI_CV_Toxic3,
    AI_CV_Toxic2,
    AI_CV_Toxic4,
    AI_CV_Toxic_End,
    AI_CV_LightScreen_ScoreDown2,
    AI_CV_LightScreen_SpecialTypeList,
    AI_CV_LightScreen_End,
    AI_CV_Rest4,
    AI_CV_Rest2,
    AI_CV_Rest_End,
    AI_CV_Rest6,
    AI_CV_Rest3,
    AI_CV_Rest5,
    AI_CV_Rest7,
    AI_CV_SuperFang_End,
    AI_CV_Trap2,
    AI_CV_Trap_End,
    AI_CV_HighCrit_End,
    AI_CV_HighCrit2,
    AI_CV_Confuse_End,
    AI_CV_Confuse2,
    AI_CV_Reflect_ScoreDown2,
    AI_CV_Reflect_PhysicalTypeList,
    AI_CV_Reflect_End,
    AI_CV_Poison_ScoreDown1,
    AI_CV_Poison_End,
    AI_CV_Paralyze2,
    AI_CV_Paralyze_End,
    AI_CV_VitalThrow_End,
    AI_CV_VitalThrow2,
    AI_CV_Substitute4,
    AI_CV_Substitute3,
    AI_CV_Substitute2,
    AI_CV_Substitute_End,
    AI_CV_Substitute5,
    AI_CV_Substitute6,
    AI_CV_Substitute7,
    AI_CV_Substitute8,
    AI_CV_Recharge_ScoreDown1,
    AI_CV_Recharge2,
    AI_CV_Recharge_End,
    AI_CV_Disable_End,
    AI_CV_Disable2,
    AI_CV_Counter_ScoreDown1,
    AI_CV_Counter2,
    AI_CV_Counter3,
    AI_CV_Counter5,
    AI_CV_Counter4,
    AI_CV_Counter_PhysicalTypeList,
    AI_CV_Counter_End,
    AI_CV_Counter6,
    AI_CV_Encore2,
    AI_CV_Encore_ScoreDown2,
    AI_CV_Encore_EncouragedMovesToEncore,
    AI_CV_Encore_End,
    AI_CV_PainSplit_ScoreDown1,
    AI_CV_PainSplit2,
    AI_CV_PainSplit_End,
    AI_CV_LockOn_End,
    AI_CV_DestinyBond_End,
    AI_CV_DestinyBond2,
    AI_CV_DestinyBond3,
    AI_CV_Flail2,
    AI_CV_Flail_ScoreDown1,
    AI_CV_Flail_End,
    AI_CV_Flail_ScoreUp1,
    AI_CV_Flail3,
    AI_CV_HealBell_End,
    AI_CV_Thief_EncourageItemsToSteal,
    AI_CV_Thief_ScoreDown2,
    AI_CV_Thief_End,
    AI_CV_Curse4,
    AI_CV_Curse_End,
    AI_CV_Curse2,
    AI_CV_Curse3,
    AI_CV_Protect_ScoreDown2,
    AI_CV_Protect3,
    AI_CV_Protect_ScoreUp2,
    AI_CV_Protect2,
    AI_CV_Protect_End,
    AI_CV_Foresight2,
    AI_CV_Foresight3,
    AI_CV_Foresight_End,
    AI_CV_Endure2,
    AI_CV_Endure3,
    AI_CV_Endure_End,
    AI_CV_BatonPass2,
    AI_CV_BatonPass5,
    AI_CV_BatonPass3,
    AI_CV_BatonPass_End,
    AI_CV_BatonPass4,
    AI_CV_BatonPass7,
    AI_CV_BatonPass_ScoreDown2,
    AI_CV_BatonPass8,
    AI_CV_Pursuit_End,
    AI_CV_Pursuit2,
    AI_CV_RainDance2,
    AI_CV_RainDance3,
    AI_CV_RainDance_ScoreDown1,
    AI_CV_RainDance_End,
    AI_CV_SunnyDay_ScoreDown1,
    AI_CV_SunnyDay2,
    AI_CV_SunnyDay_End,
    AI_CV_BellyDrum_ScoreDown2,
    AI_CV_BellyDrum_End,
    AI_CV_PsychUp2,
    AI_CV_PsychUp_ScoreDown2,
    AI_CV_PsychUp3,
    AI_CV_PsychUp_ScoreUp1,
    AI_CV_PsychUp_End,
    AI_CV_MirrorCoat_ScoreDown1,
    AI_CV_MirrorCoat2,
    AI_CV_MirrorCoat3,
    AI_CV_MirrorCoat5,
    AI_CV_MirrorCoat4,
    AI_CV_MirrorCoat_SpecialTypeList,
    AI_CV_MirrorCoat_End,
    AI_CV_MirrorCoat6,
    AI_CV_ChargeUpMove_ScoreDown2,
    AI_CV_ChargeUpMove_End,
    AI_CV_SemiInvulnerable2,
    AI_CV_SemiInvulnerable_End,
    AI_CV_SemiInvulnerable_TryEncourage,
    AI_CV_SemiInvulnerable_CheckSandstormTypes,
    AI_CV_SemiInvulnerable_CheckIceType,
    AI_CV_SemiInvulnerable5,
    AI_CV_SandstormResistantTypes,
    AI_CV_SpitUp_End,
    AI_CV_Hail_ScoreDown1,
    AI_CV_Hail2,
    AI_CV_Hail_End,
    AI_CV_Facade_End,
    AI_CV_FocusPunch2,
    AI_CV_FocusPunch_ScoreUp1,
    AI_CV_FocusPunch3,
    AI_CV_FocusPunch_End,
    AI_CV_SmellingSalt_ScoreUp1,
    AI_CV_SmellingSalt_End,
    AI_CV_Trick_ChoiceEffects,
    AI_CV_Trick3,
    AI_CV_Trick_EffectsToEncourage,
    AI_CV_Trick4,
    AI_CV_Trick_End,
    AI_CV_Trick2,
    AI_CV_ChangeSelfAbility_AbilitiesToEncourage,
    AI_CV_ChangeSelfAbility2,
    AI_CV_ChangeSelfAbility3,
    AI_CV_ChangeSelfAbility_End,
    AI_CV_Superpower_ScoreDown1,
    AI_CV_Superpower2,
    AI_CV_Superpower_End,
    AI_CV_MagicCoat2,
    AI_CV_MagicCoat4,
    AI_CV_MagicCoat_End,
    AI_CV_Recycle_ItemsToEncourage,
    AI_CV_Recycle_ScoreDown2,
    AI_CV_Recycle_End,
    AI_CV_Revenge_ScoreDown2,
    AI_CV_Revenge_End,
    AI_CV_BrickBreak_ScoreUp1,
    AI_CV_BrickBreak_End,
    AI_CV_KnockOff_End,
    AI_CV_Endeavor_ScoreDown1,
    AI_CV_Endeavor2,
    AI_CV_Endeavor_End,
    AI_CV_Eruption_ScoreDown1,
    AI_CV_Eruption2,
    AI_CV_Eruption_End,
    AI_CV_Imprison_End,
    AI_CV_Refresh_ScoreDown1,
    AI_CV_Refresh_End,
    AI_CV_Snatch3,
    AI_CV_Snatch_End,
    AI_CV_Snatch2,
    AI_CV_Snatch5,
    AI_CV_Snatch4,
    AI_CV_MudSport_ScoreDown1,
    AI_CV_MudSport2,
    AI_CV_MudSport_End,
    AI_CV_Overheat_ScoreDown1,
    AI_CV_Overheat2,
    AI_CV_Overheat_End,
    AI_CV_WaterSport_ScoreDown1,
    AI_CV_WaterSport2,
    AI_CV_WaterSport_End,
    AI_CV_DragonDance2,
    AI_CV_DragonDance_End,
    AI_TryToFaint_TryToEncourageQuickAttack,
    AI_TryToFaint_End,
    AI_TryToFaint_ScoreUp4,
    AI_SetupFirstTurn_End,
    AI_SetupFirstTurn_SetupEffectsToEncourage,
    AI_PreferStrongestMove_End,
    AI_Risky_EffectsToEncourage,
    AI_Risky_End,
    AI_PreferBatonPass_End,
    AI_PreferBatonPass_GoForBatonPass,
    AI_HPAware_UserHasHighHP,
    AI_HPAware_UserHasMediumHP,
    AI_HPAware_DiscouragedEffectsWhenLowHP,
    AI_HPAware_TryToDiscourage,
    AI_HPAware_ConsiderTarget,
    AI_HPAware_DiscouragedEffectsWhenHighHP,
    AI_HPAware_DiscouragedEffectsWhenMediumHP,
    AI_HPAware_TargetHasHighHP,
    AI_HPAware_TargetHasMediumHP,
    AI_HPAware_DiscouragedEffectsWhenTargetLowHP,
    AI_HPAware_TargetTryToDiscourage,
    AI_HPAware_End,
    AI_HPAware_DiscouragedEffectsWhenTargetHighHP,
    AI_HPAware_DiscouragedEffectsWhenTargetMediumHP,
    AI_Unknown_End,
    AI_Roaming_End,
    AI_Roaming_Flee,
    AI_Safari_Flee,
    AI_FirstBattle_Flee,
};

const u32 gNativeBattlePtrsCount = 1659;
