/* Generated by tools/gen_field_effect_data.py. Do not edit. */

#include "global.h"
#include "sprite.h"
#include "constants/field_effects.h"
#include "data/field_effects/scripts_data.h"

/* The table takes the address of each referenced symbol, so each needs
 * a declaration here. A callnative target is a function returning a
 * field-effect id; a palette or sheet operand is an object. */
extern u32 FldEff_BerryTreeGrowthSparkle(void);
extern u32 FldEff_DestroyDeoxysRock(void);
extern u32 FldEff_FieldMoveShowMon(void);
extern u32 FldEff_FieldMoveShowMonInit(void);
extern u32 FldEff_FlyIn(void);
extern u32 FldEff_FlyOut(void);
extern u32 FldEff_MoveDeoxysRock(void);
extern u32 FldEff_NpcFlyOut(void);
extern u32 FldEff_PhotoFlash(void);
extern u32 FldEff_PokeballTrail(void);
extern u32 FldEff_Shadow(void);
extern u32 FldEff_SurfBlob(void);
extern u32 FldEff_UseDive(void);
extern u32 FldEff_UseSurf(void);
extern u32 FldEff_UseVsSeeker(void);
extern u32 FldEff_UseWaterfall(void);
extern u32 ShowMountainDisguiseFieldEffect(void);
extern u32 ShowSandDisguiseFieldEffect(void);
extern u32 ShowTreeDisguiseFieldEffect(void);

extern const struct SpritePalette FldEff_Ash;
extern const struct SpritePalette FldEff_BikeTireTracks;
extern const struct SpritePalette FldEff_Bubbles;
extern const struct SpritePalette FldEff_DeepSandFootprints;
extern const struct SpritePalette FldEff_Dust;
extern const struct SpritePalette FldEff_FeetInFlowingWater;
extern const struct SpritePalette FldEff_HallOfFameRecord;
extern const struct SpritePalette FldEff_HotSpringsWater;
extern const struct SpritePalette FldEff_JumpBigSplash;
extern const struct SpritePalette FldEff_JumpLongGrass;
extern const struct SpritePalette FldEff_JumpSmallSplash;
extern const struct SpritePalette FldEff_JumpTallGrass;
extern const struct SpritePalette FldEff_LavaridgeGymWarp;
extern const struct SpritePalette FldEff_LongGrass;
extern const struct SpritePalette FldEff_PokecenterHeal;
extern const struct SpritePalette FldEff_PopOutOfAsh;
extern const struct SpritePalette FldEff_Ripple;
extern const struct SpritePalette FldEff_SandFootprints;
extern const struct SpritePalette FldEff_SandPile;
extern const struct SpritePalette FldEff_ShortGrass;
extern const struct SpritePalette FldEff_Sparkle;
extern const struct SpritePalette FldEff_Splash;
extern const struct SpritePalette FldEff_TallGrass;
extern const struct SpritePalette FldEff_UnusedGrass;
extern const struct SpritePalette FldEff_UnusedGrass2;
extern const struct SpritePalette FldEff_UnusedSand;
extern const struct SpritePalette FldEff_UnusedWaterSurfacing;
extern const struct SpritePalette gSpritePalette_Ash;
extern const struct SpritePalette gSpritePalette_GeneralFieldEffect0;
extern const struct SpritePalette gSpritePalette_GeneralFieldEffect1;
extern const struct SpritePalette gSpritePalette_HofMonitor;
extern const struct SpritePalette gSpritePalette_Pokeball;
extern const struct SpritePalette gSpritePalette_PokeballGlow;
extern const struct SpritePalette gSpritePalette_SmallSparkle;

/* Address operands in the bytecode are u32 indices into this table
 * (fix #23 style): a 32-bit script operand cannot hold a 64-bit host
 * pointer. Index 0 is reserved and resolves to NULL so that a
 * misclassified operand cannot alias a real symbol. */
const void *const gNativeFieldEffectPtrs[] = {
    NULL,
    &FldEff_Shadow,
    &gSpritePalette_GeneralFieldEffect1,
    &FldEff_TallGrass,
    &FldEff_Ripple,
    &FldEff_FieldMoveShowMon,
    &FldEff_Ash,
    &FldEff_SurfBlob,
    &FldEff_UseSurf,
    &gSpritePalette_GeneralFieldEffect0,
    &FldEff_Dust,
    &FldEff_JumpTallGrass,
    &FldEff_SandFootprints,
    &FldEff_JumpBigSplash,
    &FldEff_Splash,
    &FldEff_JumpSmallSplash,
    &FldEff_LongGrass,
    &FldEff_JumpLongGrass,
    &FldEff_UnusedGrass,
    &FldEff_UnusedGrass2,
    &FldEff_UnusedSand,
    &FldEff_UnusedWaterSurfacing,
    &FldEff_BerryTreeGrowthSparkle,
    &FldEff_DeepSandFootprints,
    &gSpritePalette_PokeballGlow,
    &FldEff_PokecenterHeal,
    &ShowTreeDisguiseFieldEffect,
    &ShowMountainDisguiseFieldEffect,
    &FldEff_NpcFlyOut,
    &FldEff_FlyOut,
    &FldEff_FlyIn,
    &FldEff_FeetInFlowingWater,
    &FldEff_BikeTireTracks,
    &ShowSandDisguiseFieldEffect,
    &FldEff_SandPile,
    &FldEff_ShortGrass,
    &FldEff_HotSpringsWater,
    &FldEff_UseWaterfall,
    &FldEff_UseDive,
    &gSpritePalette_Pokeball,
    &FldEff_PokeballTrail,
    &gSpritePalette_Ash,
    &FldEff_PopOutOfAsh,
    &FldEff_LavaridgeGymWarp,
    &FldEff_Bubbles,
    &gSpritePalette_SmallSparkle,
    &FldEff_Sparkle,
    &FldEff_FieldMoveShowMonInit,
    &gSpritePalette_HofMonitor,
    &FldEff_HallOfFameRecord,
    &FldEff_UseVsSeeker,
    &FldEff_MoveDeoxysRock,
    &FldEff_DestroyDeoxysRock,
    &FldEff_PhotoFlash,
};

/* One entry per FLDEFF_* id; NULL means the effect is not ported.
 * This is the real definition: the all-NULL stub that used to live in
 * src/platform/overworld_stubs.c is deleted (fix #8). */
const u8 *const gFieldEffectScriptPointers[FLDEFF_COUNT] = {
    [FLDEFF_EXCLAMATION_MARK_ICON] = NULL,
    [FLDEFF_USE_CUT_ON_GRASS] = NULL,
    [FLDEFF_USE_CUT_ON_TREE] = NULL,
    [FLDEFF_SHADOW] = gFldEffScript_Shadow,
    [FLDEFF_TALL_GRASS] = gFldEffScript_TallGrass,
    [FLDEFF_RIPPLE] = gFldEffScript_Ripple,
    [FLDEFF_FIELD_MOVE_SHOW_MON] = gFldEffScript_FieldMoveShowMon,
    [FLDEFF_ASH] = gFldEffScript_Ash,
    [FLDEFF_SURF_BLOB] = gFldEffScript_SurfBlob,
    [FLDEFF_USE_SURF] = gFldEffScript_UseSurf,
    [FLDEFF_DUST] = gFldEffScript_Dust,
    [FLDEFF_USE_SECRET_POWER_CAVE] = gFldEffScript_UseSecretPowerCave,
    [FLDEFF_JUMP_TALL_GRASS] = gFldEffScript_JumpTallGrass,
    [FLDEFF_SAND_FOOTPRINTS] = gFldEffScript_SandFootprints,
    [FLDEFF_JUMP_BIG_SPLASH] = gFldEffScript_JumpBigSplash,
    [FLDEFF_SPLASH] = gFldEffScript_Splash,
    [FLDEFF_JUMP_SMALL_SPLASH] = gFldEffScript_JumpSmallSplash,
    [FLDEFF_LONG_GRASS] = gFldEffScript_LongGrass,
    [FLDEFF_JUMP_LONG_GRASS] = gFldEffScript_JumpLongGrass,
    [FLDEFF_UNUSED_GRASS] = gFldEffScript_UnusedGrass,
    [FLDEFF_UNUSED_GRASS_2] = gFldEffScript_UnusedGrass2,
    [FLDEFF_UNUSED_SAND] = gFldEffScript_UnusedSand,
    [FLDEFF_UNUSED_WATER_SURFACING] = gFldEffScript_UnusedWaterSurfacing,
    [FLDEFF_BERRY_TREE_GROWTH_SPARKLE] = gFldEffScript_BerryTreeGrowthSparkle,
    [FLDEFF_DEEP_SAND_FOOTPRINTS] = gFldEffScript_DeepSandFootprints,
    [FLDEFF_POKECENTER_HEAL] = gFldEffScript_PokecenterHeal,
    [FLDEFF_USE_SECRET_POWER_TREE] = gFldEffScript_UseSecretPowerTree,
    [FLDEFF_USE_SECRET_POWER_SHRUB] = gFldEffScript_UseSecretPowerShrub,
    [FLDEFF_TREE_DISGUISE] = gFldEffScript_TreeDisguise,
    [FLDEFF_MOUNTAIN_DISGUISE] = gFldEffScript_MountainDisguise,
    [FLDEFF_NPCFLY_OUT] = gFldEffScript_NpcflyOut,
    [FLDEFF_FLY_OUT] = gFldEffScript_FlyOut,
    [FLDEFF_FLY_IN] = gFldEffScript_FlyIn,
    [FLDEFF_QUESTION_MARK_ICON] = NULL,
    [FLDEFF_FEET_IN_FLOWING_WATER] = gFldEffScript_FeetInFlowingWater,
    [FLDEFF_BIKE_TIRE_TRACKS] = gFldEffScript_BikeTireTracks,
    [FLDEFF_SAND_DISGUISE] = gFldEffScript_SandDisguise,
    [FLDEFF_USE_ROCK_SMASH] = NULL,
    [FLDEFF_USE_DIG] = NULL,
    [FLDEFF_SAND_PILE] = gFldEffScript_SandPile,
    [FLDEFF_USE_STRENGTH] = NULL,
    [FLDEFF_SHORT_GRASS] = gFldEffScript_ShortGrass,
    [FLDEFF_HOT_SPRINGS_WATER] = gFldEffScript_HotSpringsWater,
    [FLDEFF_USE_WATERFALL] = gFldEffScript_UseWaterfall,
    [FLDEFF_USE_DIVE] = gFldEffScript_UseDive,
    [FLDEFF_POKEBALL] = gFldEffScript_Pokeball,
    [FLDEFF_X_ICON] = NULL,
    [FLDEFF_NOP_47] = gFldEffScript_Nop47,
    [FLDEFF_NOP_48] = gFldEffScript_Nop48,
    [FLDEFF_POP_OUT_OF_ASH] = gFldEffScript_PopOutOfAsh,
    [FLDEFF_LAVARIDGE_GYM_WARP] = gFldEffScript_LavaridgeGymWarp,
    [FLDEFF_SWEET_SCENT] = NULL,
    [FLDEFF_SAND_PILLAR] = gFldEffScript_SandPillar,
    [FLDEFF_BUBBLES] = gFldEffScript_Bubbles,
    [FLDEFF_SPARKLE] = gFldEffScript_Sparkle,
    [FLDEFF_SECRET_POWER_CAVE] = gFldEffScript_SecretPowerCave,
    [FLDEFF_SECRET_POWER_TREE] = gFldEffScript_SecretPowerTree,
    [FLDEFF_SECRET_POWER_SHRUB] = gFldEffScript_SecretPowerShrub,
    [FLDEFF_CUT_GRASS] = NULL,
    [FLDEFF_FIELD_MOVE_SHOW_MON_INIT] = gFldEffScript_FieldMoveShowMonInit,
    [FLDEFF_USE_FLY_ANCIENT_TOMB] = gFldEffScript_UseFlyAncientTomb,
    [FLDEFF_PCTURN_ON] = gFldEffScript_PcturnOn,
    [FLDEFF_HALL_OF_FAME_RECORD] = gFldEffScript_HallOfFameRecord,
    [FLDEFF_USE_TELEPORT] = NULL,
    [FLDEFF_SMILEY_FACE_ICON] = NULL,
    [FLDEFF_USE_VS_SEEKER] = gFldEffScript_UseVsSeeker,
    [FLDEFF_DOUBLE_EXCL_MARK_ICON] = NULL,
    [FLDEFF_MOVE_DEOXYS_ROCK] = gFldEffScript_MoveDeoxysRock,
    [FLDEFF_DESTROY_DEOXYS_ROCK] = gFldEffScript_DestroyDeoxysRock,
    [FLDEFF_PHOTO_FLASH] = gFldEffScript_PhotoFlash,
};
