#!/usr/bin/env python3
"""Generates tests/script_ops.h -- named opcodes for the script bytecode.

The native scripts are bytecode compiled from pret sources, and script tests need
to say "this script starts with lockall", not "byte 0 is 0x69". The names' single
source of truth is the engine's own dispatch table: `gScriptCmdTable` in
src/data/script_cmd_table.h, whose entry order IS the opcode numbering (index 0
is 0x00). Deriving from it means a handler inserted or reordered in the table
regenerates the names rather than silently shifting every script test.

Run after editing src/data/script_cmd_table.h:
    python3 tools/gen_script_ops.py
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TABLE = REPO / "src" / "data" / "script_cmd_table.h"
OUT = REPO / "tests" / "script_ops.h"


def parse_table(text):
    """Returns [(index, handler_name)] for the gScriptCmdTable initializer."""
    match = re.search(r"gScriptCmdTable\[\]\s*=\s*\{(.*?)\n\};", text, re.S)
    if match is None:
        sys.exit(f"gen_script_ops: could not find gScriptCmdTable in {TABLE}")

    entries = []
    for line in match.group(1).splitlines():
        line = line.split("//")[0].strip().rstrip(",")
        if not line or line.startswith("#"):
            continue
        entries.append(line)
    if not entries:
        sys.exit(f"gen_script_ops: gScriptCmdTable parsed as empty in {TABLE}")
    return entries


def opcode_name(handler):
    """ScrCmd_lockall -> SCR_CMD_LOCKALL."""
    name = handler
    if name.startswith("ScrCmd_"):
        name = name[len("ScrCmd_"):]
    return "SCR_CMD_" + re.sub(r"[^A-Za-z0-9]", "_", name).upper()


def main():
    entries = parse_table(TABLE.read_text())

    lines = [
        "// GENERATED by tools/gen_script_ops.py -- do not edit.",
        "//",
        "// Opcode names for the native script bytecode, derived from the engine's",
        "// own dispatch table (src/data/script_cmd_table.h): the index of an entry",
        "// in gScriptCmdTable IS its opcode. Re-run the generator after changing",
        "// that table, so shifted opcodes update the names instead of silently",
        "// invalidating every script assertion.",
        "",
        "#ifndef GUARD_TESTS_SCRIPT_OPS_H",
        "#define GUARD_TESTS_SCRIPT_OPS_H",
        "",
    ]

    seen = {}
    for index, handler in enumerate(entries):
        name = opcode_name(handler)
        if name in seen:
            # Aliases exist in the table (several names may map to one handler);
            # keep the first so the header stays unambiguous.
            continue
        seen[name] = index
        lines.append(f"#define {name:<40} 0x{index:02X}")

    lines += [
        "",
        f"#define SCR_CMD_COUNT {len(entries)}",
        "",
        "#endif // GUARD_TESTS_SCRIPT_OPS_H",
        "",
    ]

    OUT.write_text("\n".join(lines))
    print(f"gen_script_ops: {len(seen)} opcodes from {len(entries)} table entries -> "
          f"{OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
