#!/usr/bin/env python3
import json
import sys
from pathlib import Path

def main():
    root = Path(__file__).resolve().parent.parent
    layouts_json = json.loads((root / "data/layouts/layouts.json").read_text())
    groups_json = json.loads((root / "data/maps/map_groups.json").read_text())

    out_layouts_file = root / "src/data/layouts_data.h"
    out_maps_file = root / "src/data/maps_data.h"

    # -------------------------------------------------------------
    # Generate layouts_data.h
    # -------------------------------------------------------------
    with open(out_layouts_file, "w") as f:
        f.write("/* Auto-generated by tools/gen_map_data.py - DO NOT EDIT */\n\n")
        f.write('#include "global.h"\n')
        f.write('#include "global.fieldmap.h"\n')
        f.write('#include "constants/layouts.h"\n\n')

        # Forward declarations of primary and secondary tilesets
        tilesets = set()
        for layout in layouts_json["layouts"]:
            if not layout:
                continue
            if layout.get("primary_tileset") and layout["primary_tileset"] != "NULL":
                tilesets.add(layout["primary_tileset"])
            if layout.get("secondary_tileset") and layout["secondary_tileset"] != "NULL":
                tilesets.add(layout["secondary_tileset"])
        for ts in sorted(tilesets):
            f.write(f"extern const struct Tileset {ts};\n")
        f.write("\n")

        # Generate each layout
        for layout in layouts_json["layouts"]:
            if not layout:
                continue
            name = layout["name"]
            b_path = layout["border_filepath"]
            m_path = layout["blockdata_filepath"]
            f.write(f"static const u16 {name}_Border[] = INCBIN_U16(\"{b_path}\");\n")
            f.write(f"static const u16 {name}_Blockdata[] = INCBIN_U16(\"{m_path}\");\n\n")

            pri = f"&{layout['primary_tileset']}" if layout.get("primary_tileset") and layout["primary_tileset"] != "NULL" else "NULL"
            sec = f"&{layout['secondary_tileset']}" if layout.get("secondary_tileset") and layout["secondary_tileset"] != "NULL" else "NULL"

            f.write(f"const struct MapLayout {name} = {{\n")
            f.write(f"    .width = {layout['width']},\n")
            f.write(f"    .height = {layout['height']},\n")
            f.write(f"    .border = {name}_Border,\n")
            f.write(f"    .map = {name}_Blockdata,\n")
            f.write(f"    .primaryTileset = {pri},\n")
            f.write(f"    .secondaryTileset = {sec},\n")
            f.write(f"    .borderWidth = {layout.get('border_width', 2)},\n")
            f.write(f"    .borderHeight = {layout.get('border_height', 2)},\n")
            f.write(f"}};\n\n")

        # Layouts table
        f.write("const struct MapLayout *const gMapLayouts[] = {\n")
        for layout in layouts_json["layouts"]:
            if layout and layout.get("name"):
                f.write(f"    &{layout['name']},\n")
            else:
                f.write("    NULL,\n")
        f.write("};\n\n")

    print(f"Wrote {out_layouts_file}")

    # -------------------------------------------------------------
    layout_id_to_name = {}
    for layout in layouts_json["layouts"]:
        if layout and layout.get("id"):
            layout_id_to_name[layout["id"]] = layout["name"]
    all_map_names = []
    for grp in groups_json["group_order"]:
        for m in groups_json[grp]:
            all_map_names.append(m)


    with open(out_maps_file, "w") as f:
        f.write("/* Auto-generated by tools/gen_map_data.py - DO NOT EDIT */\n\n")
        f.write('#include "global.h"\n')
        f.write('#include "global.fieldmap.h"\n')
        f.write('#include "constants/maps.h"\n')
        f.write('#include "constants/map_groups.h"\n')
        f.write('#include "constants/region_map_sections.h"\n')
        f.write('#include "constants/songs.h"\n')
        f.write('#include "constants/weather.h"\n')
        f.write('#include "constants/event_objects.h"\n')
        f.write('#include "constants/event_object_movement.h"\n')
        f.write('#include "constants/trainer_types.h"\n\n')
        f.write('#include "constants/event_bg.h"\n')
        f.write("static const u8 sDummyScript[] = { 0x02 };\n\n")

        # Map forward declarations and events
        for map_name in all_map_names:
            map_path = root / f"data/maps/{map_name}/map.json"
            if not map_path.exists():
                continue
            m = json.loads(map_path.read_text())

            # Object events
            obj_events = m.get("object_events", [])
            if obj_events:
                f.write(f"static const struct ObjectEventTemplate {map_name}_ObjectEvents[] = {{\n")
                for i, obj in enumerate(obj_events):
                    f.write(f"    {{\n")
                    f.write(f"        .localId = {i + 1},\n")
                    f.write(f"        .graphicsId = {obj.get('graphics_id', '0')},\n")
                    f.write(f"        .kind = 0,\n")
                    f.write(f"        .x = {obj.get('x', 0)},\n")
                    f.write(f"        .y = {obj.get('y', 0)},\n")
                    f.write(f"        .objUnion = {{\n")
                    f.write(f"            .normal = {{\n")
                    f.write(f"                .elevation = {obj.get('elevation', 0)},\n")
                    f.write(f"                .movementType = {obj.get('movement_type', '0')},\n")
                    f.write(f"                .movementRangeX = {obj.get('movement_range_x', 0)},\n")
                    f.write(f"                .movementRangeY = {obj.get('movement_range_y', 0)},\n")
                    f.write(f"                .trainerType = {obj.get('trainer_type', '0')},\n")
                    f.write(f"                .trainerRange_berryTreeId = {obj.get('trainer_sight_or_berry_tree_id', '0')},\n")
                    f.write(f"            }}\n")
                    f.write(f"        }},\n")
                    f.write(f"        .script = sDummyScript,\n")
                    f.write(f"        .flagId = {obj.get('flag', '0')},\n")
                    f.write(f"    }},\n")
                f.write(f"}};\n\n")
            # Warp events
            warp_events = m.get("warp_events", [])
            if warp_events:
                f.write(f"static const struct WarpEvent {map_name}_WarpEvents[] = {{\n")
                for warp in warp_events:
                    f.write(f"    {{\n")
                    f.write(f"        .x = {warp.get('x', 0)},\n")
                    f.write(f"        .y = {warp.get('y', 0)},\n")
                    f.write(f"        .elevation = {warp.get('elevation', 0)},\n")
                    f.write(f"        .warpId = {warp.get('dest_warp_id', 0)},\n")
                    dest_map = warp.get('dest_map', 'MAP_NONE')
                    if dest_map != 'MAP_NONE':
                        f.write(f"        .mapNum = MAP_NUM({dest_map}),\n")
                        f.write(f"        .mapGroup = MAP_GROUP({dest_map}),\n")
                    else:
                        f.write(f"        .mapNum = 0,\n")
                        f.write(f"        .mapGroup = 0,\n")
                    f.write(f"    }},\n")
                f.write(f"}};\n\n")

            # Coord events
            coord_events = m.get("coord_events", [])
            if coord_events:
                f.write(f"static const struct CoordEvent {map_name}_CoordEvents[] = {{\n")
                for coord in coord_events:
                    f.write(f"    {{\n")
                    f.write(f"        .x = {coord.get('x', 0)},\n")
                    f.write(f"        .y = {coord.get('y', 0)},\n")
                    f.write(f"        .elevation = {coord.get('elevation', 0)},\n")
                    f.write(f"        .trigger = {coord.get('var', '0')},\n")
                    f.write(f"        .index = {coord.get('var_value', '0')},\n")
                    f.write(f"        .script = sDummyScript,\n")
                    f.write(f"    }},\n")
                f.write(f"}};\n\n")

            # BG events
            bg_events = m.get("bg_events", [])
            if bg_events:
                f.write(f"static const struct BgEvent {map_name}_BgEvents[] = {{\n")
                for bg in bg_events:
                    f.write(f"    {{\n")
                    f.write(f"        .x = {bg.get('x', 0)},\n")
                    f.write(f"        .y = {bg.get('y', 0)},\n")
                    f.write(f"        .elevation = {bg.get('elevation', 0)},\n")
                    f.write(f"        .kind = {bg.get('player_facing_dir', '0')},\n")
                    f.write(f"        .bgUnion = {{ .script = sDummyScript }},\n")
                    f.write(f"    }},\n")
                f.write(f"}};\n\n")

            # MapEvents struct
            has_shared_events = "shared_events_map" in m
            if not has_shared_events:
                f.write(f"const struct MapEvents {map_name}_MapEvents = {{\n")
                f.write(f"    .objectEventCount = {len(obj_events)},\n")
                f.write(f"    .warpCount = {len(warp_events)},\n")
                f.write(f"    .coordEventCount = {len(coord_events)},\n")
                f.write(f"    .bgEventCount = {len(bg_events)},\n")
                f.write(f"    .objectEvents = {'&' + map_name + '_ObjectEvents[0]' if obj_events else 'NULL'},\n")
                f.write(f"    .warps = {'&' + map_name + '_WarpEvents[0]' if warp_events else 'NULL'},\n")
                f.write(f"    .coordEvents = {'&' + map_name + '_CoordEvents[0]' if coord_events else 'NULL'},\n")
                f.write(f"    .bgEvents = {'&' + map_name + '_BgEvents[0]' if bg_events else 'NULL'},\n")
                f.write(f"}};\n\n")

            layout_id = m.get('layout', 'LAYOUT_PALLET_TOWN_PLAYERS_HOUSE_2F')
            layout_name = layout_id_to_name.get(layout_id, "PalletTown_PlayersHouse_2F_Layout")
            f.write(f"extern const struct MapLayout {layout_name};\n")
            ev_name = m["shared_events_map"] if has_shared_events else map_name
            f.write(f"extern const struct MapEvents {ev_name}_MapEvents;\n")

            f.write(f"const struct MapHeader {map_name} = {{\n")
            f.write(f"    .mapLayout = &{layout_name},\n")
            f.write(f"    .events = &{ev_name}_MapEvents,\n")
            f.write(f"    .mapScripts = sDummyScript,\n")
            f.write(f"    .connections = NULL,\n")
            f.write(f"    .music = {m.get('music', 'MUS_PALLET')},\n")
            f.write(f"    .mapLayoutId = {layout_id},\n")
            f.write(f"    .regionMapSectionId = {m.get('region_map_section', 'MAPSEC_PALLET_TOWN')},\n")
            f.write(f"    .cave = {1 if m.get('requires_flash') else 0},\n")
            f.write(f"    .weather = {m.get('weather', 'WEATHER_NONE')},\n")
            f.write(f"    .mapType = {m.get('map_type', 'MAP_TYPE_INDOOR')},\n")
            f.write(f"    .bikingAllowed = {1 if m.get('allow_cycling') else 0},\n")
            f.write(f"    .allowEscaping = {1 if m.get('allow_escaping') else 0},\n")
            f.write(f"    .allowRunning = {1 if m.get('allow_running') else 0},\n")
            f.write(f"    .showMapName = {1 if m.get('show_map_name') else 0},\n")
            f.write(f"    .floorNum = {m.get('floor_number', 0)},\n")
            f.write(f"    .battleType = {m.get('battle_scene', 'MAP_BATTLE_SCENE_NORMAL')},\n")
            f.write(f"}};\n\n")

        # Groups arrays
        for grp in groups_json["group_order"]:
            maps_in_grp = groups_json[grp]
            f.write(f"static const struct MapHeader *const gMapGroup_{grp}[] = {{\n")
            for m in maps_in_grp:
                f.write(f"    &{m},\n")
            f.write(f"}};\n\n")

        # gMapGroups
        f.write("const struct MapHeader *const *const gMapGroups[] = {\n")
        for grp in groups_json["group_order"]:
            f.write(f"    gMapGroup_{grp},\n")
        f.write("};\n\n")

    print(f"Wrote {out_maps_file}")

if __name__ == "__main__":
    main()
